import type { NicheConfig } from './types';

const ACCENT = '#EC4899';
const PARENT_URL = '/belleza';
const PARENT_LABEL = 'Belleza & Bienestar';

const SHARED_PRICING = {
  hasFree: true,
  tiers: [
    {
      name: 'Gratis',
      price: '$0',
      period: 'para siempre',
      features: [
        '30 reservas por mes',
        '1 profesional',
        '1 sucursal',
        'Recordatorios por WhatsApp',
        'Link de reservas personalizado',
        'Soporte por email',
      ],
    },
    {
      name: 'Profesional',
      price: '$14.999',
      period: '/mes',
      popular: true,
      features: [
        'Reservas ilimitadas',
        'Hasta 5 profesionales',
        '1 sucursal',
        'Cobro de señas con Mercado Pago',
        'Recordatorios automáticos',
        'Panel de métricas',
        'Control de finanzas',
        'Portal de empleados (hasta 3)',
        'Soporte prioritario',
      ],
    },
    {
      name: 'Business',
      price: '$29.999',
      period: '/mes',
      features: [
        'Todo lo de Profesional',
        'Profesionales ilimitados',
        'Múltiples sucursales',
        'Portal de empleados ilimitado',
        'API e integraciones',
        'Reportes avanzados',
        'Control de finanzas',
        'Gerente de cuenta dedicado',
        'Onboarding personalizado',
      ],
    },
  ],
};

const bellezaConfig: NicheConfig = {
  slug: 'belleza',
  label: 'Belleza & Bienestar',
  accent: ACCENT,
  url: PARENT_URL,
  subNiches: {
    peluquerias: {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Peluquerías — Turnos Online y Cobro Automático',
        description: 'Sistema de turnos online para peluquerías. Reservas 24/7, cobro de señas con Mercado Pago y recordatorios automáticos. Empezá gratis.',
        keywords: ['turnos peluquería online', 'sistema de reservas peluquería', 'agenda peluquería digital', 'software peluquería argentina', 'turnos online peluquería', 'cobro señas peluquería'],
      },
      pill: '✂️ Peluquerías',
      heroTitle: 'Tu peluquería llena,',
      heroSubtitle: 'sin perseguir clientes.',
      painPoints: [
        { title: 'Turnos fantasma', desc: 'Clientes que reservan por WhatsApp y no aparecen. Perdés el horario, perdés plata y no podés dar ese turno a otro.' },
        { title: 'WhatsApp colapsado', desc: 'Pasás horas respondiendo "¿tenés turno para el sábado?" mientras deberías estar cortando. Tu teléfono no para.' },
        { title: 'Agenda desorganizada', desc: 'Turnos superpuestos, horarios mal calculados y profesionales que no saben qué viene después. El caos frena tu crecimiento.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda por profesional', desc: 'Cada estilista tiene su propia agenda con servicios, horarios y duración personalizados.' },
        { icon: 'CreditCard', title: 'Cobro de señas automático', desc: 'Cobrá una seña con Mercado Pago al reservar. Sin seña, sin turno. Chau ausencias.' },
        { icon: 'Bell', title: 'Recordatorios por WhatsApp', desc: 'Tu cliente recibe un recordatorio 24hs y 2hs antes. Menos olvidos, menos huecos en la agenda.' },
        { icon: 'Globe', title: 'Link de reservas 24/7', desc: 'Compartí tu link en Instagram, Google y WhatsApp. Tus clientes reservan solos a cualquier hora.' },
        { icon: 'Users', title: 'Gestión de clientes', desc: 'Historial de turnos, preferencias y datos de contacto. Conocé a tus clientes como nunca.' },
        { icon: 'LayoutDashboard', title: 'Panel de control', desc: 'Visualizá turnos del día, ingresos, ausencias y métricas clave en un solo lugar.' },
      ],
      subIndustries: ['Corte de cabello', 'Colorimetría', 'Peinados', 'Tratamientos capilares', 'Alisados', 'Extensiones'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Desde que usamos TurnoLink, las ausencias bajaron un 80%. El cobro de seña automático cambió todo. Mis clientas reservan solas desde Instagram.', name: 'Mariana López', role: 'Dueña', business: 'Estudio MR Peluquería', image: 'https://randomuser.me/api/portraits/women/25.jpg' },
        { quote: 'Antes tenía 3 peluqueras y coordinaba todo por WhatsApp. Era un desastre. Ahora cada una tiene su agenda y yo solo superviso.', name: 'Valentina Gómez', role: 'Directora', business: 'Valentina Hair Studio', image: 'https://randomuser.me/api/portraits/women/26.jpg' },
        { quote: 'Mis clientes aman poder reservar a las 11 de la noche. Y yo amo no tener que responder a las 11 de la noche.', name: 'Lucas Martínez', role: 'Peluquero', business: 'Lucas Barber & Style', image: 'https://randomuser.me/api/portraits/men/25.jpg' },
      ],
      faqs: [
        { q: '¿Puedo configurar servicios con distinta duración?', a: 'Sí. Cada servicio tiene su propia duración. Un corte puede durar 30 min y una colorimetría 2 horas. La agenda se ajusta automáticamente.' },
        { q: '¿Funciona con varios peluqueros?', a: 'Sí. Cada profesional tiene su propia agenda, servicios y horarios. Tus clientes eligen a quién reservarle.' },
        { q: '¿Cómo cobro la seña?', a: 'Se configura un monto de seña por servicio. Cuando el cliente reserva, paga con Mercado Pago. La plata va directo a tu cuenta.' },
        { q: '¿Puedo compartir el link en Instagram?', a: 'Sí. Tenés un link personalizado que podés poner en tu bio de Instagram, Google Maps, WhatsApp o donde quieras.' },
        { q: '¿Qué pasa si un cliente cancela?', a: 'Podés definir políticas de cancelación con anticipación mínima. Si cancela fuera de plazo, la seña queda a tu favor.' },
        { q: '¿Necesito tarjeta de crédito para empezar?', a: 'No. El plan Gratis es 100% gratis, para siempre. No pedimos tarjeta ni datos bancarios.' },
        { q: '¿Puedo bloquear horarios para almorzar?', a: 'Sí. Configurás bloques de descanso, feriados y vacaciones para cada profesional individualmente.' },
      ],
      cta: { headline: 'Llenà tu agenda', subtitle: 'sin levantar el teléfono.', description: 'Creá tu cuenta gratis, cargá tus servicios y compartí tu link. En 5 minutos tus clientes reservan solos.' },
    },

    barberias: {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Barberías — Agenda Digital y Cobro de Señas',
        description: 'Sistema de turnos online para barberías. Reservas 24/7, cobro automático y gestión de barberos. Empezá gratis.',
        keywords: ['turnos barbería online', 'agenda barbería digital', 'sistema reservas barbería', 'software barbería argentina', 'turnos barbero online'],
      },
      pill: '💈 Barberías',
      heroTitle: 'Tu barbería organizada,',
      heroSubtitle: 'tu tiempo recuperado.',
      painPoints: [
        { title: 'Cola interminable', desc: 'Clientes que llegan sin turno y se van porque hay mucha espera. Perdés ventas todos los días por no tener sistema.' },
        { title: 'Barberos sin agenda', desc: 'Cada barbero maneja sus turnos como puede. No sabés quién tiene hueco, quién está lleno ni cuánto factura cada uno.' },
        { title: 'No-shows constantes', desc: 'Reservan un sábado a la tarde — el horario más rentable — y no aparecen. Sin seña, no hay consecuencia.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda por barbero', desc: 'Cada barbero tiene su agenda con sus servicios, precios y disponibilidad. Sin conflictos, sin superposiciones.' },
        { icon: 'CreditCard', title: 'Señas automáticas', desc: 'El cliente paga al reservar. Si no viene, la seña queda. Eliminá los no-shows de raíz.' },
        { icon: 'Bell', title: 'Recordatorios', desc: 'WhatsApp automático 24hs antes. Tu cliente no se olvida y vos no tenés que recordarle.' },
        { icon: 'Globe', title: 'Link para redes', desc: 'Un link que ponés en tu bio de Instagram y listo. Tus clientes reservan cuando quieren.' },
        { icon: 'Timer', title: 'Tiempos por servicio', desc: 'Corte 30 min, barba 20 min, combo 45 min. La agenda calcula todo automáticamente.' },
        { icon: 'LayoutDashboard', title: 'Métricas del negocio', desc: 'Cuántos turnos, cuánta plata, qué barbero rinde más. Todo en un panel claro.' },
      ],
      subIndustries: ['Corte de pelo', 'Barba y afeitado', 'Cejas', 'Tratamientos capilares', 'Grooming', 'Colorimetría masculina'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Antes perdía 3 horas por día en WhatsApp coordinando turnos. Ahora mis clientes reservan solos y yo me enfoco en cortar.', name: 'Lucas Fernández', role: 'Barbero', business: 'Barber Shop LF', image: 'https://randomuser.me/api/portraits/men/26.jpg' },
        { quote: 'Tengo 4 barberos y cada uno maneja su agenda en TurnoLink. Cero conflictos, cero superposiciones.', name: 'Tomás Ruiz', role: 'Dueño', business: 'The Barber House', image: 'https://randomuser.me/api/portraits/men/27.jpg' },
        { quote: 'El sábado era un caos. Ahora con las señas, solo vienen los que realmente van a venir.', name: 'Diego Sánchez', role: 'Barbero', business: 'DStyle Barbería', image: 'https://randomuser.me/api/portraits/men/28.jpg' },
      ],
      faqs: [
        { q: '¿Puedo poner servicios combo (corte + barba)?', a: 'Sí. Creás un servicio combo con la duración total y el precio que quieras. El cliente lo ve como una opción más al reservar.' },
        { q: '¿Funciona con walk-ins?', a: 'Sí. Podés agregar turnos manuales para clientes que llegan sin reserva. La agenda se actualiza en tiempo real.' },
        { q: '¿Mis barberos pueden gestionar su propia agenda?', a: 'Sí. Cada barbero puede ver sus turnos, bloquear horarios y gestionar su disponibilidad desde su celular.' },
        { q: '¿Puedo ver cuánto factura cada barbero?', a: 'Sí. El panel te muestra métricas por profesional: turnos, ingresos, ausencias y más.' },
        { q: '¿Se puede usar desde el celular?', a: 'Sí. TurnoLink es 100% responsive. Funciona perfecto desde el celular, tablet o computadora.' },
        { q: '¿Puedo poner precios diferentes para cada barbero?', a: 'Sí. Cada profesional puede tener sus propios servicios y precios.' },
      ],
      cta: { headline: 'Digitalizá tu barbería', subtitle: 'en 5 minutos.', description: 'Creá tu cuenta gratis, sumá a tus barberos y empezá a recibir reservas con cobro automático.' },
    },

    'centros-de-estetica': {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Centros de Estética — Reservas y Cobros Online',
        description: 'Sistema de turnos para centros de estética. Gestión de gabinetes, cobro de señas y agenda online. Empezá gratis.',
        keywords: ['turnos centro estética online', 'sistema reservas estética', 'agenda centro estética', 'software estética argentina', 'turnos estética online'],
      },
      pill: '✨ Centros de Estética',
      heroTitle: 'Tu centro de estética',
      heroSubtitle: 'funcionando en automático.',
      painPoints: [
        { title: 'Gabinetes descoordinados', desc: 'Tenés múltiples profesionales en varios gabinetes y coordinar todo por WhatsApp es imposible. Se superponen turnos.' },
        { title: 'Tratamientos largos, agenda frágil', desc: 'Un tratamiento facial dura 1 hora. Si el cliente no viene, perdés el gabinete y el profesional por 1 hora completa.' },
        { title: 'Falta de seguimiento', desc: 'No sabés qué cliente hizo qué tratamiento, cuándo vino por última vez ni cuándo debería volver.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de gabinetes', desc: 'Asigná profesionales a gabinetes, controlá la disponibilidad y evitá superposiciones.' },
        { icon: 'CreditCard', title: 'Señas por tratamiento', desc: 'Cobrá señas proporcionales al valor del tratamiento. Más caro el servicio, mayor la seña.' },
        { icon: 'Users', title: 'Historial de cliente', desc: 'Cada cliente tiene su ficha con historial de tratamientos, notas y próxima visita recomendada.' },
        { icon: 'CalendarCheck', title: 'Agenda multi-profesional', desc: 'Esteticistas, cosmetólogas y masajistas. Cada una con su agenda y servicios propios.' },
        { icon: 'Bell', title: 'Recordatorios inteligentes', desc: 'Recordá turnos y también sugirí a clientes que vuelvan cuando su tratamiento lo requiere.' },
        { icon: 'LayoutDashboard', title: 'Reportes de rendimiento', desc: 'Qué tratamientos generan más ingresos, qué profesional tiene mejor ocupación, qué horarios están vacíos.' },
      ],
      subIndustries: ['Tratamientos faciales', 'Tratamientos corporales', 'Rejuvenecimiento', 'Limpieza profunda', 'Radiofrecuencia', 'Dermaplaning'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Gestionamos 3 gabinetes con 6 profesionales. TurnoLink nos organizó el centro completo. Las clientas reservan solas.', name: 'Carolina Ruiz', role: 'Directora', business: 'Spa Esencia Estética', image: 'https://randomuser.me/api/portraits/women/27.jpg' },
        { quote: 'Las señas cambiaron todo. Antes perdíamos 5 turnos por semana. Ahora las ausencias son casi cero.', name: 'Lucía Mendoza', role: 'Esteticista', business: 'Luce Centro de Estética', image: 'https://randomuser.me/api/portraits/women/28.jpg' },
        { quote: 'Puedo ver cuántos tratamientos hizo cada profesional y cuánto facturó. Eso antes era imposible.', name: 'Andrea Vega', role: 'Dueña', business: 'Vega Estética Avanzada', image: 'https://randomuser.me/api/portraits/women/29.jpg' },
      ],
      faqs: [
        { q: '¿Puedo gestionar múltiples gabinetes?', a: 'Sí. Cada gabinete tiene su disponibilidad y podés asignar profesionales a cada uno sin conflictos.' },
        { q: '¿Se puede configurar señas diferentes por tratamiento?', a: 'Sí. Un tratamiento de $50.000 puede tener una seña de $10.000 y uno de $20.000 una seña de $5.000.' },
        { q: '¿Puedo guardar notas por cliente?', a: 'Sí. Cada cliente tiene una ficha donde podés anotar alergias, preferencias, productos usados y más.' },
        { q: '¿Funciona para paquetes de sesiones?', a: 'Sí. Podés crear paquetes de sesiones y llevar registro de cuántas usó cada cliente.' },
        { q: '¿Mis profesionales ven solo sus turnos?', a: 'Sí. Cada profesional accede solo a su agenda. Vos como dueña ves todo el centro.' },
        { q: '¿Se integra con redes sociales?', a: 'Sí. Tenés un link de reservas que podés poner en Instagram, Facebook, Google Maps o tu web.' },
      ],
      cta: { headline: 'Organizá tu centro', subtitle: 'de estética por completo.', description: 'Creá tu cuenta gratis, configurá gabinetes y profesionales. En minutos tus clientas reservan solas.' },
    },

    'unas-nail-bars': {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Nail Bars y Uñas — Agenda Online y Señas',
        description: 'Sistema de turnos para salones de uñas y nail bars. Reservas online, cobro de señas y gestión de manicuristas. Empezá gratis.',
        keywords: ['turnos uñas online', 'agenda nail bar', 'sistema reservas manicura', 'software uñas esculpidas', 'turnos manicurista online'],
      },
      pill: '💅 Uñas & Nail Bars',
      heroTitle: 'Tu nail bar siempre lleno,',
      heroSubtitle: 'sin perder ni un turno.',
      painPoints: [
        { title: 'Servicios que duran horas', desc: 'Unas esculpidas pueden llevar 2 horas. Si la clienta no viene, perdés media mañana completa.' },
        { title: 'Demasiados mensajes', desc: 'Entre consultas de diseños, precios y disponibilidad, tu WhatsApp es un caos imposible de gestionar.' },
        { title: 'Falta de organización', desc: 'No sabés qué manicurista está libre, qué clienta pidió qué diseño ni cuándo vuelve cada una.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda por manicurista', desc: 'Cada profesional con su agenda, servicios y tiempos. Sin cruces ni superposiciones.' },
        { icon: 'CreditCard', title: 'Señas para evitar pérdidas', desc: 'Servicios largos requieren señas altas. Protegé tu tiempo con cobro automático al reservar.' },
        { icon: 'Timer', title: 'Duración por servicio', desc: 'Semi 45 min, esculpidas 2hs, pedicura 1h. La agenda calcula todo automáticamente.' },
        { icon: 'Globe', title: 'Reservas desde Instagram', desc: 'Tus clientas ven tu trabajo en Instagram y reservan directo. Sin intermediarios.' },
        { icon: 'Bell', title: 'Recordatorios automáticos', desc: 'WhatsApp 24hs antes para que tu clienta no se olvide y vos no pierdas el turno.' },
        { icon: 'Users', title: 'Ficha de clienta', desc: 'Historial de servicios, diseños preferidos, alergias y frecuencia de visita.' },
      ],
      subIndustries: ['Manicura', 'Pedicura', 'Uñas esculpidas', 'Semipermanente', 'Nail art', 'Press on nails', 'Kapping'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Mis clientas reservan solas desde mi Instagram. Ya no pierdo tiempo con mensajes. El negocio creció un 40%.', name: 'Camila Torres', role: 'Dueña', business: 'Cami Nails Studio', image: 'https://randomuser.me/api/portraits/women/30.jpg' },
        { quote: 'Con las señas, las ausencias bajaron a casi cero. Antes perdía 3 o 4 turnos de esculpidas por semana.', name: 'Sol García', role: 'Manicurista', business: 'Sol Nail Bar', image: 'https://randomuser.me/api/portraits/women/31.jpg' },
        { quote: 'Tengo 3 manicuristas y cada una gestiona su agenda. Yo solo miro el panel y veo cómo va todo.', name: 'Paula Ríos', role: 'Directora', business: 'Nail Lab BA', image: 'https://randomuser.me/api/portraits/women/32.jpg' },
      ],
      faqs: [
        { q: '¿Puedo configurar servicios de distinta duración?', a: 'Sí. Semipermanente 45 min, esculpidas 2 horas, pedicura 1 hora. Cada servicio tiene su tiempo.' },
        { q: '¿Funciona para salones con varias manicuristas?', a: 'Sí. Cada profesional tiene su propia agenda y servicios. Las clientas eligen a quién reservarle.' },
        { q: '¿Las clientas pueden elegir el diseño al reservar?', a: 'Podés agregar un campo de notas donde la clienta describe lo que quiere o sube una foto de referencia.' },
        { q: '¿Puedo cobrar señas diferentes por servicio?', a: 'Sí. Una seña de $3.000 para semi y $8.000 para esculpidas. Vos decidís.' },
        { q: '¿Funciona desde el celular?', a: 'Sí. Tanto vos como tus clientas pueden usar TurnoLink perfectamente desde el celular.' },
        { q: '¿Puedo ver estadísticas de mi negocio?', a: 'Sí. Turnos, ingresos, ausencias, servicios más pedidos y rendimiento por profesional.' },
      ],
      cta: { headline: 'Llenà tu agenda de uñas', subtitle: 'sin esfuerzo.', description: 'Creá tu cuenta gratis, cargá tus servicios y empezá a recibir reservas con señas automáticas.' },
    },

    'pestanas-cejas': {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Pestañas y Cejas — Turnos y Señas Online',
        description: 'Sistema de turnos para estudios de pestañas y cejas. Reservas online, cobro de señas y recordatorios automáticos. Empezá gratis.',
        keywords: ['turnos pestañas online', 'agenda cejas', 'sistema reservas lash', 'turnos extensiones pestañas', 'reservas lifting cejas'],
      },
      pill: '👁️ Pestañas & Cejas',
      heroTitle: 'Tu agenda de lash',
      heroSubtitle: 'siempre organizada.',
      painPoints: [
        { title: 'Turnos largos perdidos', desc: 'Un set de pestañas lleva 2 horas. Si la clienta no viene, perdés medio turno de trabajo.' },
        { title: 'Coordinación manual', desc: 'Mensajes ida y vuelta para confirmar tipo de extensión, curvatura y horario. Todo por WhatsApp.' },
        { title: 'Retoques sin control', desc: 'No sabés cuándo hiciste el último set, cuándo debería volver ni qué tipo de extensión usa cada clienta.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda especializada', desc: 'Servicios de lash y cejas con duraciones exactas. Set completo, retoque, lifting, laminado.' },
        { icon: 'CreditCard', title: 'Señas por servicio', desc: 'Protegé tus turnos largos con señas automáticas. Si no viene, la seña es tuya.' },
        { icon: 'Users', title: 'Ficha de clienta', desc: 'Curvatura, grosor, tipo de extensión, alergias. Todo registrado para cada clienta.' },
        { icon: 'Bell', title: 'Recordatorios de retoque', desc: 'Avisale a tu clienta cuando es momento de hacer el retoque. Fidelizá sin esfuerzo.' },
        { icon: 'Globe', title: 'Reservas desde redes', desc: 'Link directo desde tu Instagram. Tus clientas ven tus trabajos y reservan al instante.' },
        { icon: 'Timer', title: 'Tiempos precisos', desc: 'Set completo 2hs, retoque 1h, lifting 45min. La agenda nunca se superpone.' },
      ],
      subIndustries: ['Extensiones clásicas', 'Volumen ruso', 'Lifting de pestañas', 'Laminado de cejas', 'Diseño de cejas', 'Tinte de cejas'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Mis clientas reservan solas y ya saben que sin seña no hay turno. Las ausencias desaparecieron.', name: 'Florencia Díaz', role: 'Lash artist', business: 'Flor Lashes Studio', image: 'https://randomuser.me/api/portraits/women/33.jpg' },
        { quote: 'Tengo el historial de cada clienta: qué curvatura usa, cuándo fue el último set. Es una herramienta increíble.', name: 'Micaela Sosa', role: 'Especialista en cejas', business: 'Mica Brow Bar', image: 'https://randomuser.me/api/portraits/women/34.jpg' },
        { quote: 'El recordatorio automático de retoque me genera 10 turnos extra por mes. Plata que antes perdía.', name: 'Julieta Romero', role: 'Dueña', business: 'Juli Lash & Brow', image: 'https://randomuser.me/api/portraits/women/35.jpg' },
      ],
      faqs: [
        { q: '¿Puedo separar servicios de pestañas y cejas?', a: 'Sí. Creás categorías de servicios: pestañas (set, retoque, lifting) y cejas (diseño, laminado, tinte).' },
        { q: '¿Puedo guardar las preferencias de cada clienta?', a: 'Sí. Curvatura, grosor, largo, tipo de extensión y cualquier nota que necesites.' },
        { q: '¿Funciona el recordatorio de retoque?', a: 'Sí. Podés configurar un recordatorio automático a las 2-3 semanas del último servicio.' },
        { q: '¿La seña se descuenta del total?', a: 'Eso lo definís vos. Podés descontarla del precio final o usarla como garantía anti-ausencia.' },
        { q: '¿Se puede usar para un home studio?', a: 'Sí. TurnoLink funciona perfecto para estudios de una sola persona. El plan Gratis es ideal para empezar.' },
        { q: '¿Puedo bloquear tiempo entre turnos?', a: 'Sí. Configurás un buffer entre turnos para preparar materiales o descansar.' },
      ],
      cta: { headline: 'Profesionalizá tu estudio', subtitle: 'de pestañas y cejas.', description: 'Creá tu cuenta gratis y empezá a recibir reservas con cobro automático. En 5 minutos estás lista.' },
    },

    depilacion: {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Depilación — Turnos Online y Cobro Automático',
        description: 'Sistema de turnos para centros de depilación. Agenda online, cobro de señas y gestión de cabinas. Empezá gratis.',
        keywords: ['turnos depilación online', 'agenda depilación láser', 'sistema reservas depilación', 'turnos depilación definitiva', 'software depilación argentina'],
      },
      pill: '⚡ Depilación',
      heroTitle: 'Tu centro de depilación',
      heroSubtitle: 'con agenda llena y cero ausencias.',
      painPoints: [
        { title: 'Ausencias en cadena', desc: 'Clientes que reservan sesiones de depilación y no vienen. Perdés la cabina, el insumo y el tiempo.' },
        { title: 'Sesiones que requieren frecuencia', desc: 'La depilación láser necesita sesiones regulares. Sin seguimiento, tus clientes se pierden y no terminan el tratamiento.' },
        { title: 'Cabinas desorganizadas', desc: 'Múltiples cabinas, múltiples profesionales y zonas del cuerpo con tiempos distintos. Coordinar es un dolor de cabeza.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de cabinas', desc: 'Cada cabina con su disponibilidad. Asigná profesionales y evitá superposiciones.' },
        { icon: 'CreditCard', title: 'Señas obligatorias', desc: 'Sin seña no hay turno. Protegé tus cabinas y tu tiempo con cobro automático.' },
        { icon: 'Timer', title: 'Duración por zona', desc: 'Axilas 15 min, piernas completas 45 min, cuerpo completo 90 min. La agenda calcula sola.' },
        { icon: 'Bell', title: 'Seguimiento de sesiones', desc: 'Recordá a tus clientes cuándo les toca la próxima sesión para mantener la frecuencia.' },
        { icon: 'Users', title: 'Historial de cliente', desc: 'Zonas tratadas, sesiones realizadas, fototipo de piel y observaciones por sesión.' },
        { icon: 'CalendarCheck', title: 'Paquetes de sesiones', desc: 'Vendé paquetes de 6 u 8 sesiones y llevá el registro de cuántas usó cada cliente.' },
      ],
      subIndustries: ['Depilación láser', 'Depilación con cera', 'IPL', 'Depilación definitiva', 'Luz pulsada', 'Electrólisis'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Tenemos 4 cabinas y 3 profesionales. Antes era un caos de planillas. Ahora TurnoLink gestiona todo solo.', name: 'Patricia Suárez', role: 'Directora', business: 'LaserPro Centro', image: 'https://randomuser.me/api/portraits/women/36.jpg' },
        { quote: 'Las señas eliminaron las ausencias. Antes perdíamos 8 turnos por semana. Ahora máximo 1.', name: 'Romina Castillo', role: 'Dueña', business: 'Romina Depilación Láser', image: 'https://randomuser.me/api/portraits/women/37.jpg' },
        { quote: 'El seguimiento de sesiones me ayuda a que mis clientas no abandonen el tratamiento. Más completados = más ingresos.', name: 'María Elena Paz', role: 'Esteticista', business: 'ME Estética Avanzada', image: 'https://randomuser.me/api/portraits/women/38.jpg' },
      ],
      faqs: [
        { q: '¿Puedo vender paquetes de sesiones?', a: 'Sí. Creás paquetes de 6, 8 o las sesiones que quieras. El sistema lleva el conteo automáticamente.' },
        { q: '¿Funciona para depilación láser y cera?', a: 'Sí. Creás servicios distintos con duración y precio diferente para cada tipo de depilación.' },
        { q: '¿Puedo gestionar varias cabinas?', a: 'Sí. Cada cabina tiene su disponibilidad y podés asignar profesionales a cada una.' },
        { q: '¿Se puede configurar por zona del cuerpo?', a: 'Sí. Axilas, piernas, bikini, espalda — cada zona como servicio con su duración y precio.' },
        { q: '¿El sistema recuerda a los clientes su próxima sesión?', a: 'Sí. Configurás recordatorios automáticos para que vuelvan en el intervalo correcto.' },
        { q: '¿Puedo ver estadísticas de mis cabinas?', a: 'Sí. Ocupación por cabina, ingresos por profesional, servicios más pedidos y más.' },
      ],
      cta: { headline: 'Digitalizá tu centro', subtitle: 'de depilación hoy.', description: 'Creá tu cuenta gratis, configurá tus cabinas y servicios. En minutos empezás a recibir reservas.' },
    },

    'spa-relax': {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Spa y Relax — Reservas Online y Gestión Completa',
        description: 'Sistema de reservas para spa. Gestión de circuitos, cabinas y profesionales con cobro automático. Empezá gratis.',
        keywords: ['reservas spa online', 'sistema turnos spa', 'agenda spa digital', 'software spa argentina', 'reservas spa relax'],
      },
      pill: '🧖 Spa & Relax',
      heroTitle: 'Tu spa organizado,',
      heroSubtitle: 'tus clientes relajados.',
      painPoints: [
        { title: 'Circuitos sin control', desc: 'Sauna, jacuzzi, ducha escocesa — cada zona con capacidad limitada. Sin sistema, se sobresatura.' },
        { title: 'Experiencia arruinada', desc: 'Clientes que llegan y no hay lugar. Otros que pagaron y no vinieron. La experiencia premium se resiente.' },
        { title: 'Múltiples servicios, un caos', desc: 'Masajes, faciales, circuito de aguas, pedicura. Coordinar todo con planillas es insostenible.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de espacios', desc: 'Controlá la capacidad de cada zona: sauna, jacuzzi, sala de relax. Sin sobrecupo.' },
        { icon: 'CreditCard', title: 'Cobro anticipado', desc: 'Cobrá el circuito completo o una seña al reservar. Garantizá la asistencia.' },
        { icon: 'CalendarCheck', title: 'Reservas de circuito', desc: 'Tu cliente elige día, horario y circuito. Todo automático, todo organizado.' },
        { icon: 'Users', title: 'Experiencia premium', desc: 'Ficha de cliente con preferencias, alergias e historial. Ofrecé un servicio personalizado.' },
        { icon: 'Timer', title: 'Bloques horarios', desc: 'Circuitos de 2hs, masajes de 1h, faciales de 45min. Cada servicio con su tiempo exacto.' },
        { icon: 'LayoutDashboard', title: 'Dashboard de operación', desc: 'Ocupación por zona, ingresos del día, reservas pendientes. Todo en un vistazo.' },
      ],
      subIndustries: ['Circuitos de agua', 'Sauna y vapor', 'Jacuzzi', 'Day spa', 'Wellness', 'Terapias alternativas'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Nuestro spa tiene 5 zonas distintas. TurnoLink nos permite controlar la capacidad de cada una sin esfuerzo.', name: 'Marina Paz', role: 'Gerente', business: 'Spa Armonía', image: 'https://randomuser.me/api/portraits/women/39.jpg' },
        { quote: 'Los clientes reservan su circuito y pagan online. Llegan relajados porque saben que su lugar está asegurado.', name: 'Roberto Figueroa', role: 'Director', business: 'Aqua Spa & Wellness', image: 'https://randomuser.me/api/portraits/men/29.jpg' },
        { quote: 'Antes teníamos overbooking todos los fines de semana. Ahora cada zona tiene su capacidad y no se supera.', name: 'Sofía Ledesma', role: 'Dueña', business: 'Sofía Day Spa', image: 'https://randomuser.me/api/portraits/women/40.jpg' },
      ],
      faqs: [
        { q: '¿Puedo limitar la capacidad por zona?', a: 'Sí. Si tu sauna tiene capacidad para 8 personas, solo se reservan 8 lugares por bloque horario.' },
        { q: '¿Funciona para paquetes spa?', a: 'Sí. Creás paquetes que combinan circuito + masaje + facial con un precio especial.' },
        { q: '¿Mis clientes pueden elegir horario de circuito?', a: 'Sí. Ven los horarios disponibles y eligen el que les conviene. Todo automático.' },
        { q: '¿Se puede cobrar el circuito completo por adelantado?', a: 'Sí. Podés cobrar el total o solo una seña. Vos decidís la política.' },
        { q: '¿Funciona para day spa y wellness?', a: 'Sí. Cualquier espacio con capacidad limitada y servicios por hora funciona perfecto con TurnoLink.' },
        { q: '¿Puedo ofrecer gift cards o vouchers?', a: 'Actualmente podés crear servicios especiales como "voucher regalo" que tus clientes pueden reservar para otros.' },
      ],
      cta: { headline: 'Elevá la experiencia', subtitle: 'de tu spa.', description: 'Creá tu cuenta gratis, configurá tus zonas y servicios. Reservas online con cobro automático.' },
    },

    masajes: {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Masajistas — Agenda Online y Cobro de Señas',
        description: 'Sistema de turnos para masajistas y estudios de masajes. Reservas 24/7, cobro automático y recordatorios. Empezá gratis.',
        keywords: ['turnos masajista online', 'agenda masajes digital', 'sistema reservas masajista', 'turnos masajes online', 'software masajista argentina'],
      },
      pill: '💆 Masajes',
      heroTitle: 'Tu agenda de masajes',
      heroSubtitle: 'llena y organizada.',
      painPoints: [
        { title: 'Horarios muertos', desc: 'Clientes que no vienen y vos esperando con la camilla lista. Cada hueco es plata que perdés.' },
        { title: 'Coordinación por chat', desc: 'Mensajes a toda hora preguntando disponibilidad. Respondés mientras atendés y perdés el foco.' },
        { title: 'Sin registro de clientes', desc: 'No sabés qué tipo de masaje prefiere cada cliente, sus lesiones ni cuándo vino por última vez.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda inteligente', desc: 'Tus clientes ven tu disponibilidad real y reservan solos. Sin mensajes, sin llamadas.' },
        { icon: 'CreditCard', title: 'Señas automáticas', desc: 'Cobrá una seña al reservar. Si no viene, la seña es tuya. Cero pérdidas.' },
        { icon: 'Timer', title: 'Duración personalizada', desc: 'Relajante 60 min, descontracturante 45 min, piedras calientes 90 min. Todo configurado.' },
        { icon: 'Bell', title: 'Recordatorios', desc: 'WhatsApp automático para que tu cliente no se olvide del turno.' },
        { icon: 'Users', title: 'Ficha de paciente', desc: 'Lesiones, zonas a evitar, preferencia de presión. Todo registrado para cada sesión.' },
        { icon: 'Globe', title: 'Presencia online', desc: 'Link profesional para compartir en redes, Google Maps y grupos de WhatsApp.' },
      ],
      subIndustries: ['Masaje relajante', 'Descontracturante', 'Drenaje linfático', 'Piedras calientes', 'Reflexología', 'Shiatsu', 'Deportivo'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Trabajo sola y TurnoLink me organizó la vida. Mis clientes reservan solos y yo me enfoco en lo que sé hacer.', name: 'Natalia Herrera', role: 'Masajista', business: 'Nati Masajes Terapéuticos', image: 'https://randomuser.me/api/portraits/women/41.jpg' },
        { quote: 'Las señas fueron un antes y después. Ya no pierdo turnos de 1 hora porque alguien se olvidó.', name: 'Martín Acosta', role: 'Masajista', business: 'Martín Masajes Deportivos', image: 'https://randomuser.me/api/portraits/men/30.jpg' },
        { quote: 'Tengo la ficha de cada cliente con sus preferencias. Cuando llegan, ya sé exactamente qué necesitan.', name: 'Laura Benítez', role: 'Terapeuta', business: 'Espacio Zen Masajes', image: 'https://randomuser.me/api/portraits/women/42.jpg' },
      ],
      faqs: [
        { q: '¿Puedo ofrecer distintos tipos de masaje?', a: 'Sí. Creás cada tipo como un servicio con su duración, precio y descripción propia.' },
        { q: '¿Funciona para un masajista independiente?', a: 'Perfecto. El plan Gratis es ideal para profesionales que trabajan solos.' },
        { q: '¿Puedo dejar un tiempo entre turnos?', a: 'Sí. Configurás un buffer de 15-30 min entre sesiones para preparar la camilla y descansar.' },
        { q: '¿Se pueden guardar notas sobre el cliente?', a: 'Sí. Zonas sensibles, lesiones, preferencia de presión. Todo queda en la ficha del cliente.' },
        { q: '¿Los clientes eligen el tipo de masaje al reservar?', a: 'Sí. Ven la lista de servicios con descripción y precio, eligen y reservan.' },
        { q: '¿Puedo ofrecer bonos de sesiones?', a: 'Sí. Creás paquetes de 5 o 10 sesiones a precio especial y el sistema lleva el conteo.' },
      ],
      cta: { headline: 'Organizá tu agenda', subtitle: 'de masajes sin esfuerzo.', description: 'Creá tu cuenta gratis, cargá tus servicios y compartí tu link. En 5 minutos empezás a recibir reservas.' },
    },

    bronceado: {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Bronceado — Reservas Online para Camas Solares',
        description: 'Sistema de reservas para centros de bronceado y camas solares. Turnos online, cobro automático y gestión de cabinas. Empezá gratis.',
        keywords: ['turnos bronceado online', 'reservas camas solares', 'sistema turnos bronceado', 'agenda bronceado digital', 'software centro bronceado'],
      },
      pill: '☀️ Bronceado',
      heroTitle: 'Tu centro de bronceado',
      heroSubtitle: 'siempre con camas ocupadas.',
      painPoints: [
        { title: 'Camas vacías', desc: 'Sesiones de 15-20 minutos con alta rotación. Si no gestionás bien, tenés camas vacías todo el día.' },
        { title: 'Turnos por WhatsApp', desc: 'Clientes que quieren turno urgente y vos no podés responder porque estás atendiendo.' },
        { title: 'Sin control de sesiones', desc: 'No sabés cuántas sesiones hizo cada cliente esta semana ni si está respetando los intervalos recomendados.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de camas', desc: 'Cada cama como recurso independiente. Controlá disponibilidad y evitá superposiciones.' },
        { icon: 'Timer', title: 'Sesiones cortas y rotativas', desc: 'Turnos de 15, 20 o 30 min con rotación automática. Maximizá la ocupación de cada cama.' },
        { icon: 'CreditCard', title: 'Cobro por sesión', desc: 'Cobrá la sesión o un paquete al reservar. Sin sorpresas para nadie.' },
        { icon: 'Users', title: 'Control de frecuencia', desc: 'Registrá sesiones por cliente y controlá que respeten los intervalos entre sesiones.' },
        { icon: 'CalendarCheck', title: 'Reservas instantáneas', desc: 'Tu cliente abre el link, elige cama y horario, paga y listo. En 30 segundos.' },
        { icon: 'Bell', title: 'Recordatorios', desc: 'Avisale a tu cliente 2hs antes para que no se olvide y vos no pierdas la cama.' },
      ],
      subIndustries: ['Camas solares', 'Spray tan', 'Bronceado artificial', 'Cabinas UV', 'Bronceado express'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Tengo 6 camas y antes era imposible coordinar. Ahora las clientes reservan solas y las camas están siempre ocupadas.', name: 'Yanina Peralta', role: 'Dueña', business: 'Sun Bronceado', image: 'https://randomuser.me/api/portraits/women/43.jpg' },
        { quote: 'Los paquetes de sesiones me generan ingresos por adelantado. Las clientas compran y vuelven.', name: 'Daniela Moreno', role: 'Gerente', business: 'Golden Tan Studio', image: 'https://randomuser.me/api/portraits/women/45.jpg' },
        { quote: 'El control de frecuencia es genial. Sé exactamente cuántas sesiones hizo cada clienta y cuándo puede volver.', name: 'Silvina Ramos', role: 'Dueña', business: 'Bronze BA', image: 'https://randomuser.me/api/portraits/women/46.jpg' },
      ],
      faqs: [
        { q: '¿Puedo gestionar varias camas?', a: 'Sí. Cada cama es un recurso con su disponibilidad. Las clientas eligen qué cama y horario quieren.' },
        { q: '¿Funciona para sesiones cortas de 15 minutos?', a: 'Sí. Configurás la duración exacta de cada tipo de sesión. Ideal para alta rotación.' },
        { q: '¿Puedo vender paquetes de sesiones?', a: 'Sí. Paquetes de 10, 20 o las que quieras. El sistema descuenta automáticamente cada uso.' },
        { q: '¿Puedo controlar la frecuencia de uso?', a: 'Sí. Registrás cada sesión y podés ver cuántas hizo cada clienta en la semana.' },
        { q: '¿Las clientas pueden reservar desde el celular?', a: 'Sí. Todo funciona perfecto desde el celular. Reservan en 30 segundos.' },
        { q: '¿Se integra con Mercado Pago?', a: 'Sí. El cobro se hace automáticamente por Mercado Pago. La plata va directo a tu cuenta.' },
      ],
      cta: { headline: 'Maximizá la ocupación', subtitle: 'de tus camas.', description: 'Creá tu cuenta gratis, configurá tus camas y tipos de sesión. Reservas y cobros automáticos.' },
    },

    cosmetologia: {
      accent: ACCENT,
      parentNicheUrl: PARENT_URL,
      parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Cosmetología — Agenda Online y Gestión de Pacientes',
        description: 'Sistema de turnos para cosmetólogas. Gestión de pacientes, cobro de señas y agenda online. Empezá gratis.',
        keywords: ['turnos cosmetología online', 'agenda cosmetóloga digital', 'sistema reservas cosmetología', 'turnos skincare online', 'software cosmetología argentina'],
      },
      pill: '💧 Cosmetología',
      heroTitle: 'Tu consultorio de cosmetología',
      heroSubtitle: 'profesional y organizado.',
      painPoints: [
        { title: 'Protocolos sin seguimiento', desc: 'Cada paciente tiene un protocolo distinto. Sin sistema, perdés el hilo de qué tratamiento hizo y qué sigue.' },
        { title: 'Turnos cancelados', desc: 'Tratamientos de 1 hora cancelados a último momento. Sin seña, no hay forma de proteger tu tiempo.' },
        { title: 'Información dispersa', desc: 'Tipo de piel, alergias, productos usados, fotos de evolución. Todo en papelitos o notas del celular.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda profesional', desc: 'Turnos por tipo de tratamiento con duración exacta. Limpieza, peeling, microdermoabrasión.' },
        { icon: 'CreditCard', title: 'Señas por tratamiento', desc: 'Protegé tu tiempo. Cobrar seña elimina las cancelaciones de último momento.' },
        { icon: 'Users', title: 'Ficha de paciente', desc: 'Tipo de piel, alergias, historial de tratamientos, productos utilizados. Todo en un lugar.' },
        { icon: 'Bell', title: 'Seguimiento inteligente', desc: 'Recordá a tus pacientes cuándo les toca la siguiente sesión de su protocolo.' },
        { icon: 'Shield', title: 'Consentimientos', desc: 'Adjuntá consentimientos informados al perfil del paciente para tener todo documentado.' },
        { icon: 'LayoutDashboard', title: 'Métricas del consultorio', desc: 'Tratamientos más pedidos, ingresos, tasa de retorno y rendimiento mensual.' },
      ],
      subIndustries: ['Limpieza profunda', 'Peelings', 'Microdermoabrasión', 'Dermaplaning', 'Skincare', 'Anti-age', 'Manchas'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Ahora tengo toda la historia clínica de cada paciente en la app. Sé exactamente qué hicimos y qué sigue.', name: 'Analía Pereyra', role: 'Cosmetóloga', business: 'Analía Skin Consultorio', image: 'https://randomuser.me/api/portraits/women/47.jpg' },
        { quote: 'Las señas me devolvieron la tranquilidad. Mi agenda está llena de pacientes que realmente vienen.', name: 'Cecilia Navarro', role: 'Cosmetóloga', business: 'Ceci Cosmetología Integral', image: 'https://randomuser.me/api/portraits/women/48.jpg' },
        { quote: 'Mis pacientes reservan solas desde mi Instagram. Yo me enfoco en los tratamientos, no en la agenda.', name: 'Valeria Ortiz', role: 'Dueña', business: 'VO Cosmetología', image: 'https://randomuser.me/api/portraits/women/49.jpg' },
      ],
      faqs: [
        { q: '¿Puedo registrar el tipo de piel del paciente?', a: 'Sí. Cada paciente tiene una ficha completa con tipo de piel, alergias, sensibilidades y notas de cada sesión.' },
        { q: '¿Funciona para protocolos de varias sesiones?', a: 'Sí. Podés crear paquetes de sesiones y llevar el registro de avance de cada paciente.' },
        { q: '¿Puedo adjuntar fotos de evolución?', a: 'Podés usar las notas para registrar la evolución. Las fotos podés guardarlas con referencia al turno.' },
        { q: '¿Se puede configurar por tipo de tratamiento?', a: 'Sí. Limpieza 60 min, peeling 45 min, microdermoabrasión 30 min. Cada uno con su precio y tiempo.' },
        { q: '¿Es seguro para datos de pacientes?', a: 'Sí. Los datos están encriptados y solo vos tenés acceso a la información de tus pacientes.' },
        { q: '¿Puedo gestionar más de un consultorio?', a: 'Sí. Con el plan Business podés manejar múltiples sucursales desde una sola cuenta.' },
      ],
      cta: { headline: 'Profesionalizá tu consultorio', subtitle: 'de cosmetología.', description: 'Creá tu cuenta gratis, cargá tus tratamientos y gestioná a tus pacientes de forma profesional.' },
    },
  },
};

export default bellezaConfig;
