import type { NicheConfig } from './types';

const ACCENT = '#22C55E';
const PARENT_URL = '/deportes';
const PARENT_LABEL = 'Deportes & Recreación';

const SHARED_PRICING = {
  hasFree: true,
  tiers: [
    {
      name: 'Gratis',
      price: '$0',
      period: 'para siempre',
      features: ['30 reservas por mes', '1 cancha o espacio', '1 sucursal', 'Recordatorios por WhatsApp', 'Link de reservas personalizado', 'Soporte por email'],
    },
    {
      name: 'Profesional',
      price: '$14.999',
      period: '/mes',
      popular: true,
      features: ['Reservas ilimitadas', 'Hasta 5 canchas o espacios', '1 sucursal', 'Cobro de señas con Mercado Pago', 'Recordatorios automáticos', 'Panel de métricas', 'Control de finanzas', 'Portal de empleados (hasta 3)', 'Soporte prioritario'],
    },
    {
      name: 'Business',
      price: '$29.999',
      period: '/mes',
      features: ['Todo lo de Profesional', 'Canchas/espacios ilimitados', 'Múltiples sucursales', 'Portal de empleados ilimitado', 'API e integraciones', 'Reportes avanzados', 'Control de finanzas', 'Gerente de cuenta dedicado', 'Onboarding personalizado'],
    },
  ],
};

const deportesConfig: NicheConfig = {
  slug: 'deportes',
  label: 'Deportes & Recreación',
  accent: ACCENT,
  url: PARENT_URL,
  subNiches: {
    'canchas-de-futbol': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Canchas de Fútbol — Reservas Online y Cobro Automático',
        description: 'Sistema de reservas para canchas de fútbol. Gestión de múltiples canchas, cobro de señas y turnos online 24/7. Empezá gratis.',
        keywords: ['reservas cancha fútbol online', 'sistema turnos cancha fútbol', 'alquiler cancha fútbol 5', 'software canchas fútbol argentina', 'reservas fútbol online'],
      },
      pill: '⚽ Canchas de Fútbol',
      heroTitle: 'Tus canchas siempre ocupadas,',
      heroSubtitle: 'tu teléfono siempre libre.',
      painPoints: [
        { title: 'Grupos que cancelan', desc: 'Reservan la cancha para las 21hs y a las 20:30 avisan que no juntan los jugadores. Cancha vacía, plata perdida.' },
        { title: 'WhatsApp imposible', desc: '50 grupos de WhatsApp preguntando "¿hay cancha para el jueves?". No podés responder a todos.' },
        { title: 'Múltiples canchas, un caos', desc: 'Fútbol 5, 7 y 11. Cada cancha con su horario, su precio y su disponibilidad. Coordinar es un dolor de cabeza.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión multi-cancha', desc: 'Fútbol 5, 7, 8, 11 — cada cancha como recurso independiente con su precio y horario.' },
        { icon: 'CreditCard', title: 'Seña obligatoria', desc: 'Sin seña no hay cancha. El grupo paga al reservar y si cancela tarde, la seña es tuya.' },
        { icon: 'CalendarCheck', title: 'Reservas 24/7', desc: 'Tu link abierto las 24 horas. Los grupos reservan a cualquier hora sin llamarte.' },
        { icon: 'Bell', title: 'Recordatorios al grupo', desc: 'WhatsApp automático al organizador 24hs antes. Sin excusas de "me olvidé".' },
        { icon: 'Timer', title: 'Bloques horarios', desc: 'Turnos de 1 hora o 1:30. Configurá la duración y el sistema organiza todo.' },
        { icon: 'LayoutDashboard', title: 'Panel de ocupación', desc: 'Qué canchas están llenas, cuáles tienen hueco, cuánto facturaste hoy. Todo en un vistazo.' },
      ],
      subIndustries: ['Fútbol 5', 'Fútbol 7', 'Fútbol 8', 'Fútbol 11', 'Baby fútbol', 'Torneos y ligas'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Tengo 4 canchas y antes era un caos de WhatsApp. Ahora los grupos reservan y pagan solos. Las cancelaciones bajaron un 90%.', name: 'Marcelo Gómez', role: 'Dueño', business: 'El Potrero Fútbol', image: 'https://randomuser.me/api/portraits/men/39.jpg' },
        { quote: 'La seña fue un antes y después. Ya no pierdo canchas vacías porque alguien no juntó el equipo.', name: 'Nicolás Peralta', role: 'Gerente', business: 'Canchas NP', image: 'https://randomuser.me/api/portraits/men/40.jpg' },
        { quote: 'Mis clientes aman reservar desde el celular. Y yo amo no tener que responder 100 mensajes por día.', name: 'Hernán Acosta', role: 'Dueño', business: 'Gol de Barrio', image: 'https://randomuser.me/api/portraits/men/41.jpg' },
      ],
      faqs: [
        { q: '¿Puedo gestionar canchas de distinto tamaño?', a: 'Sí. Cada cancha es un recurso independiente con su propio precio, horario y duración de turno.' },
        { q: '¿Cómo funciona la seña?', a: 'El grupo paga la seña al reservar con Mercado Pago. Si cancela fuera de plazo, la seña es tuya.' },
        { q: '¿Funciona para turnos fijos semanales?', a: 'Sí. Podés reservar turnos recurrentes para equipos que juegan siempre el mismo día y hora.' },
        { q: '¿Puedo poner precios distintos según el horario?', a: 'Sí. Precio de día, de noche, fin de semana. Todo configurable por cancha.' },
        { q: '¿Los clientes ven la disponibilidad en tiempo real?', a: 'Sí. Ven qué horarios están libres y reservan al instante.' },
        { q: '¿Se puede usar para torneos?', a: 'Podés bloquear horarios para torneos y gestionar las canchas durante esos eventos.' },
      ],
      cta: { headline: 'Llenà tus canchas', subtitle: 'sin esfuerzo.', description: 'Creá tu cuenta gratis, cargá tus canchas y empezá a recibir reservas con cobro automático.' },
    },

    'canchas-de-padel': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Canchas de Pádel — Reservas Online y Señas',
        description: 'Sistema de reservas para canchas de pádel. Turnos online, cobro de señas y gestión de múltiples canchas. Empezá gratis.',
        keywords: ['reservas pádel online', 'turnos cancha pádel', 'sistema reservas pádel', 'alquiler cancha pádel', 'software pádel argentina'],
      },
      pill: '🏸 Canchas de Pádel',
      heroTitle: 'Tus canchas de pádel',
      heroSubtitle: 'reservadas sin parar.',
      painPoints: [
        { title: 'Horarios pico desperdiciados', desc: 'Las 19-21hs son oro. Si alguien reserva y no viene, perdés el mejor horario del día.' },
        { title: 'Gestión de múltiples canchas', desc: 'Cancha 1, 2, 3. Indoor, outdoor. Cada una con su precio. Coordinar todo es agotador.' },
        { title: 'Clientes que piden cambio de hora', desc: 'Mensajes de "¿me podés pasar a las 20?" constantemente. Tu WhatsApp no para.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Multi-cancha', desc: 'Cada cancha como recurso: indoor, outdoor, iluminada. Con precio y disponibilidad propia.' },
        { icon: 'CreditCard', title: 'Señas automáticas', desc: 'El jugador paga al reservar. Si cancela tarde, la seña queda. Chau horarios perdidos.' },
        { icon: 'CalendarCheck', title: 'Reservas instantáneas', desc: 'Tu cliente abre el link, elige cancha y hora, paga y listo. En 1 minuto.' },
        { icon: 'Globe', title: 'Link para redes', desc: 'Compartí en Instagram, Google Maps y grupos de pádel. Reservas 24/7.' },
        { icon: 'Timer', title: 'Turnos de 1h o 1:30', desc: 'Configurá la duración del turno según tu cancha y demanda.' },
        { icon: 'LayoutDashboard', title: 'Métricas de ocupación', desc: 'Ocupación por cancha, por día, por horario. Sabé exactamente dónde está tu oportunidad.' },
      ],
      subIndustries: ['Pádel indoor', 'Pádel outdoor', 'Clases de pádel', 'Torneos', 'Pádel nocturno', 'Alquiler de paletas'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Tengo 6 canchas de pádel y la ocupación subió un 30% desde que implementamos reservas online con seña.', name: 'Federico Ríos', role: 'Dueño', business: 'Pádel Zone', image: 'https://randomuser.me/api/portraits/men/42.jpg' },
        { quote: 'Los horarios pico ya no se pierden. Con la seña, los jugadores vienen o pierden la plata.', name: 'Sebastián Alonso', role: 'Gerente', business: 'Smash Pádel Club', image: 'https://randomuser.me/api/portraits/men/43.jpg' },
        { quote: 'Ya no respondo WhatsApp todo el día. Los jugadores reservan solos y yo me enfoco en el club.', name: 'Martín Lucero', role: 'Dueño', business: 'Pádel ML', image: 'https://randomuser.me/api/portraits/men/44.jpg' },
      ],
      faqs: [
        { q: '¿Puedo diferenciar canchas indoor y outdoor?', a: 'Sí. Cada cancha es un recurso independiente con su nombre, tipo, precio y disponibilidad.' },
        { q: '¿Funciona para clases y torneos?', a: 'Sí. Creás servicios de clase con su duración y bloqueás horarios para torneos.' },
        { q: '¿Puedo poner precios por horario?', a: 'Sí. Horario valle más barato, horario pico más caro. Todo configurable.' },
        { q: '¿Los jugadores pueden cancelar?', a: 'Sí. Definís cuántas horas antes pueden cancelar sin perder la seña.' },
        { q: '¿Funciona para clubes con pádel y otras actividades?', a: 'Sí. Podés tener canchas de pádel, tenis y fútbol, todo gestionado desde una cuenta.' },
        { q: '¿Se integra con Mercado Pago?', a: 'Sí. Cobros automáticos directo a tu cuenta de Mercado Pago.' },
      ],
      cta: { headline: 'Maximizá la ocupación', subtitle: 'de tus canchas de pádel.', description: 'Creá tu cuenta gratis, cargá tus canchas y recibí reservas con cobro automático.' },
    },

    tenis: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Tenis — Reservas de Canchas y Clases Online',
        description: 'Sistema de reservas para canchas de tenis. Turnos online, clases con coach y cobro automático. Empezá gratis.',
        keywords: ['reservas tenis online', 'turnos cancha tenis', 'sistema reservas club tenis', 'alquiler cancha tenis', 'software tenis argentina'],
      },
      pill: '🎾 Tenis',
      heroTitle: 'Tu club de tenis',
      heroSubtitle: 'con canchas siempre reservadas.',
      painPoints: [
        { title: 'Canchas vacías entre clases', desc: 'Las horas entre clases quedan libres. Sin sistema de reserva fácil, nadie las aprovecha.' },
        { title: 'Coordinación de clases', desc: 'Clases individuales, grupales, torneos. Coordinar coaches, canchas y horarios es un rompecabezas.' },
        { title: 'No-shows en hora pico', desc: 'Reservan la cancha de las 18hs y no aparecen. Otro jugador que quería esa hora se quedó sin cancha.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de canchas', desc: 'Polvo de ladrillo, cemento, sintética. Cada cancha con su tipo, precio y disponibilidad.' },
        { icon: 'Users', title: 'Clases con coach', desc: 'Individual, grupal, clínicas. Asigná coaches a canchas y horarios sin conflictos.' },
        { icon: 'CreditCard', title: 'Señas por reserva', desc: 'El jugador paga al reservar. Sin excusas, sin canchas vacías.' },
        { icon: 'CalendarCheck', title: 'Reservas online', desc: 'Socios y visitantes reservan desde el link a cualquier hora.' },
        { icon: 'Timer', title: 'Turnos de 1h', desc: 'Singles y dobles con la misma duración. La agenda es siempre clara.' },
        { icon: 'LayoutDashboard', title: 'Dashboard del club', desc: 'Ocupación, ingresos por cancha, clases dictadas y rendimiento de coaches.' },
      ],
      subIndustries: ['Singles', 'Dobles', 'Clases individuales', 'Clases grupales', 'Torneos', 'Mini tenis'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Las canchas que quedaban vacías entre clases ahora se llenan con reservas online. Subimos un 25% la ocupación.', name: 'Carlos Vega', role: 'Director deportivo', business: 'Tennis Club Vega', image: 'https://randomuser.me/api/portraits/men/45.jpg' },
        { quote: 'Los coaches tienen su agenda organizada. Saben qué cancha, qué alumno y a qué hora. Sin confusiones.', name: 'Analía Ferreyra', role: 'Coordinadora', business: 'Racket Club', image: 'https://randomuser.me/api/portraits/women/58.jpg' },
        { quote: 'La seña eliminó los no-shows. Ahora cada cancha reservada es una cancha que se usa.', name: 'Juan Manuel Ríos', role: 'Dueño', business: 'JM Tenis', image: 'https://randomuser.me/api/portraits/men/46.jpg' },
      ],
      faqs: [
        { q: '¿Puedo gestionar canchas de distinto tipo?', a: 'Sí. Polvo de ladrillo, cemento, sintética. Cada una con su precio y disponibilidad.' },
        { q: '¿Funciona para clases con coach?', a: 'Sí. Creás servicios de clase asignados a un coach específico en una cancha específica.' },
        { q: '¿Puedo tener precios para socios y no socios?', a: 'Sí. Creás diferentes tipos de servicio con precios diferenciados.' },
        { q: '¿Se puede reservar para dobles?', a: 'Sí. Es la misma reserva de cancha. El jugador puede invitar a sus compañeros.' },
        { q: '¿Funciona para torneos internos?', a: 'Podés bloquear canchas para torneos y gestionar los horarios de los partidos.' },
        { q: '¿Los socios pueden ver la disponibilidad en tiempo real?', a: 'Sí. Ven qué canchas están libres y reservan al instante.' },
      ],
      cta: { headline: 'Modernizá tu club', subtitle: 'de tenis.', description: 'Creá tu cuenta gratis, cargá tus canchas y coaches. Reservas online con cobro automático.' },
    },

    basquet: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Básquet — Reservas de Canchas Online',
        description: 'Sistema de reservas para canchas de básquet. Turnos por hora, ligas recreativas y cobro automático. Empezá gratis.',
        keywords: ['reservas cancha básquet online', 'turnos básquet', 'alquiler cancha básquet', 'reservas basquet argentina'],
      },
      pill: '🏀 Básquet',
      heroTitle: 'Tus canchas de básquet',
      heroSubtitle: 'siempre en juego.',
      painPoints: [
        { title: 'Baja ocupación', desc: 'Las canchas de básquet son difíciles de llenar comparadas con fútbol. Sin reservas fáciles, quedan vacías.' },
        { title: 'Grupos que no aparecen', desc: 'Reservan para jugar un 3 vs 3 y no vienen. Sin seña, no hay consecuencia.' },
        { title: 'Sin visibilidad online', desc: 'Nadie sabe que alquilás canchas de básquet. No tenés presencia digital.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Canchas por recurso', desc: 'Cancha completa, media cancha, espacio para tiros. Cada formato como recurso.' },
        { icon: 'CreditCard', title: 'Señas para garantizar', desc: 'El grupo paga al reservar. Si no viene, la seña queda.' },
        { icon: 'Globe', title: 'Presencia online', desc: 'Link en Google Maps, redes e Instagram. Que te encuentren y reserven al instante.' },
        { icon: 'CalendarCheck', title: 'Reservas simples', desc: 'Elegí cancha, hora y pagá. En 1 minuto la cancha está reservada.' },
        { icon: 'Timer', title: 'Bloques flexibles', desc: 'Turnos de 1h, 1:30 o 2h según demanda y formato de juego.' },
        { icon: 'LayoutDashboard', title: 'Control de ocupación', desc: 'Sabé cuándo están vacías tus canchas y cuándo están llenas.' },
      ],
      subIndustries: ['Básquet 3x3', 'Básquet 5x5', 'Ligas recreativas', 'Clases', 'Práctica libre', 'Torneos'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Pusimos nuestras canchas online y la ocupación subió un 40%. La gente no sabía que alquilábamos.', name: 'Rodrigo Paz', role: 'Dueño', business: 'Hoop Center BA', image: 'https://randomuser.me/api/portraits/men/47.jpg' },
        { quote: 'Las señas fueron clave. Los grupos se comprometen y las canchas se llenan.', name: 'Ezequiel Torres', role: 'Gerente', business: 'BasketPoint', image: 'https://randomuser.me/api/portraits/men/48.jpg' },
        { quote: 'Ahora gestiono las canchas de básquet y las de fútbol desde la misma app. Todo mucho más simple.', name: 'Leandro Díaz', role: 'Dueño', business: 'Multi Deportes LD', image: 'https://randomuser.me/api/portraits/men/49.jpg' },
      ],
      faqs: [
        { q: '¿Puedo alquilar media cancha?', a: 'Sí. Creás media cancha como un recurso independiente con su propio horario y precio.' },
        { q: '¿Funciona para ligas recreativas?', a: 'Sí. Bloqueás horarios para las fechas de la liga y gestionás las reservas de cada equipo.' },
        { q: '¿Puedo tener canchas de básquet y fútbol juntas?', a: 'Sí. Cada cancha es un recurso independiente. Podés mezclar deportes sin problemas.' },
        { q: '¿La seña se puede descontar del total?', a: 'Eso lo definís vos. Puede ser a cuenta del total o como garantía anti-ausencia.' },
        { q: '¿Funciona desde el celular?', a: 'Sí. Todo 100% responsive. Tus clientes reservan desde el celular en segundos.' },
        { q: '¿Puedo ofrecer descuentos en horarios vacíos?', a: 'Sí. Creás precios especiales para horarios de baja demanda y los ofrecés con un link.' },
      ],
      cta: { headline: 'Llenà tus canchas', subtitle: 'de básquet.', description: 'Creá tu cuenta gratis, cargá tus canchas y empezá a recibir reservas con seña.' },
    },

    'estudios-de-danza': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Estudios de Danza — Reservas de Clases Online',
        description: 'Sistema de reservas para estudios de danza. Clases, salas y eventos con cobro automático. Empezá gratis.',
        keywords: ['reservas clases danza online', 'sistema turnos estudio danza', 'agenda escuela baile', 'software estudio danza argentina'],
      },
      pill: '💃 Estudios de Danza',
      heroTitle: 'Tu estudio de danza',
      heroSubtitle: 'con clases siempre llenas.',
      painPoints: [
        { title: 'Clases con cupos vacíos', desc: 'Abrís una clase para 15 y vienen 5. Sin sistema de reserva previa, no sabés cuántos van a venir.' },
        { title: 'Alumnos que no avisan', desc: 'Faltan sin avisar y vos tenés la sala lista para más gente que no viene.' },
        { title: 'Gestión de múltiples disciplinas', desc: 'Salsa, contemporáneo, jazz, hip hop. Cada clase con su profesor, sala y horario. Coordinar es un caos.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Reserva de clases', desc: 'Tus alumnos reservan lugar en la clase. Vos sabés exactamente cuántos vienen.' },
        { icon: 'Building2', title: 'Gestión de salas', desc: 'Sala grande, sala chica, sala con espejo. Cada una con su capacidad y disponibilidad.' },
        { icon: 'CreditCard', title: 'Cobro por clase', desc: 'Cobrá la clase al reservar. Solo vienen los que pagaron.' },
        { icon: 'Users', title: 'Gestión de profesores', desc: 'Cada profesor con su agenda, disciplinas y salas asignadas.' },
        { icon: 'Bell', title: 'Recordatorio de clase', desc: 'WhatsApp automático 24hs antes para que tus alumnos no se olviden.' },
        { icon: 'LayoutDashboard', title: 'Métricas del estudio', desc: 'Clases más populares, tasa de asistencia, ingresos por disciplina.' },
      ],
      subIndustries: ['Salsa y bachata', 'Tango', 'Contemporáneo', 'Jazz', 'Hip hop', 'Ballet', 'Danza árabe'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Ahora sé exactamente cuántos alumnos vienen a cada clase. Puedo planificar y optimizar mis salas.', name: 'María José Ledesma', role: 'Directora', business: 'MJ Dance Studio', image: 'https://randomuser.me/api/portraits/women/59.jpg' },
        { quote: 'El cobro por clase eliminó las faltas sin aviso. Mis ingresos se estabilizaron un montón.', name: 'Alejandro Moreno', role: 'Profesor', business: 'Moreno Danza', image: 'https://randomuser.me/api/portraits/men/50.jpg' },
        { quote: 'Gestiono 4 disciplinas con 6 profesores en 3 salas. Sin TurnoLink sería imposible.', name: 'Luciana Costa', role: 'Dueña', business: 'Espacio Danza LC', image: 'https://randomuser.me/api/portraits/women/60.jpg' },
      ],
      faqs: [
        { q: '¿Puedo limitar cupos por clase?', a: 'Sí. Cada clase tiene su capacidad máxima. Cuando se llena, nadie más puede reservar.' },
        { q: '¿Funciona con pases mensuales?', a: 'Podés crear servicios para clase suelta o paquetes de clases por mes.' },
        { q: '¿Cada profesor tiene su propia agenda?', a: 'Sí. Cada profesor ve solo sus clases y alumnos inscriptos.' },
        { q: '¿Puedo gestionar varias disciplinas?', a: 'Sí. Salsa, tango, contemporáneo — todas como servicios distintos con su profesor y sala.' },
        { q: '¿Los alumnos pueden ver el calendario de clases?', a: 'Sí. Ven todas las clases disponibles con día, hora, profesor y cupos restantes.' },
        { q: '¿Se puede usar para eventos y workshops?', a: 'Sí. Creás eventos especiales con fecha, duración y cupo como cualquier otro servicio.' },
      ],
      cta: { headline: 'Llenà las clases', subtitle: 'de tu estudio de danza.', description: 'Creá tu cuenta gratis, cargá tus clases y que tus alumnos reserven lugar con pago anticipado.' },
    },

    'gimnasios-por-clase': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Gimnasios por Clase — Reservas Online de Clases',
        description: 'Sistema de reservas para gimnasios por clase. CrossFit, funcional, spinning con cobro automático y gestión de cupos. Empezá gratis.',
        keywords: ['reservas clase gimnasio online', 'sistema turnos crossfit', 'agenda gimnasio funcional', 'software box crossfit argentina'],
      },
      pill: '🏋️ Gimnasios por Clase',
      heroTitle: 'Tu box o gimnasio',
      heroSubtitle: 'con clases completas siempre.',
      painPoints: [
        { title: 'Clases vacías o sobrepobladas', desc: 'Sin reserva previa, a veces tenés 5 personas y a veces 30. No podés planificar.' },
        { title: 'Alumnos que no vienen', desc: 'Reservan la clase de las 7am y no aparecen. Otro que quería venir se quedó afuera.' },
        { title: 'Cobro mensual sin control', desc: 'Pagaron el mes pero no venés a las clases. No sabés si usan el pase o no.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Reserva de clases', desc: 'Cada alumno reserva su lugar. Vos sabés cuántos vienen y podés planificar el WOD.' },
        { icon: 'Users', title: 'Control de cupos', desc: 'Clase de 20 personas máximo. Cuando se llena, se cierra. Sin sobrecupo.' },
        { icon: 'CreditCard', title: 'Pago por clase o pase', desc: 'Clase suelta o pase mensual con límite de clases. Todo automatizado.' },
        { icon: 'Bell', title: 'Recordatorios', desc: 'Tu alumno recibe un aviso antes de la clase. Menos faltas, mejores clases.' },
        { icon: 'Timer', title: 'Clases de 1h', desc: 'WOD, funcional, spinning, yoga. Cada disciplina con su horario y coach.' },
        { icon: 'LayoutDashboard', title: 'Métricas del box', desc: 'Clases más populares, tasa de asistencia, alumnos activos y retención.' },
      ],
      subIndustries: ['CrossFit', 'Funcional', 'Spinning', 'HIIT', 'Yoga', 'Pilates', 'Boxeo fitness'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Antes las clases de las 7am venían 8 personas y las de las 19 venían 35. Ahora todo está equilibrado con cupos.', name: 'Matías López', role: 'Coach', business: 'Warrior Box CrossFit', image: 'https://randomuser.me/api/portraits/men/51.jpg' },
        { quote: 'Mis alumnos reservan clase desde el celular en 10 segundos. Yo sé exactamente quién viene.', name: 'Rocío Fernández', role: 'Dueña', business: 'FitSpace Studio', image: 'https://randomuser.me/api/portraits/women/61.jpg' },
        { quote: 'El sistema de pases con límite de clases me ayudó a monetizar mejor. Antes todos pagaban lo mismo sin importar asistencia.', name: 'Gonzalo Herrera', role: 'Director', business: 'Herrera Fitness', image: 'https://randomuser.me/api/portraits/men/52.jpg' },
      ],
      faqs: [
        { q: '¿Puedo limitar cupos por clase?', a: 'Sí. CrossFit 15 personas, funcional 20, spinning 25. Cada clase con su límite.' },
        { q: '¿Funciona con pases mensuales?', a: 'Sí. Pase de 12 clases, 20 clases o ilimitado. El sistema descuenta cada reserva.' },
        { q: '¿Puedo tener varias disciplinas?', a: 'Sí. CrossFit, funcional, spinning, yoga. Cada una con su coach, horario y cupo.' },
        { q: '¿Qué pasa si un alumno cancela?', a: 'Se libera el cupo y otro alumno puede tomar su lugar. Definís cuántas horas antes puede cancelar.' },
        { q: '¿Los alumnos ven el calendario de clases?', a: 'Sí. Ven todas las clases de la semana con coach, disciplina y cupos disponibles.' },
        { q: '¿Puedo ver qué alumnos no están viniendo?', a: 'Sí. Las métricas te muestran asistencia por alumno para que puedas contactar a los inactivos.' },
      ],
      cta: { headline: 'Organizá tu box', subtitle: 'o gimnasio por clase.', description: 'Creá tu cuenta gratis, cargá tus clases y que tus alumnos reserven lugar.' },
    },

    'entrenadores-personales': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Entrenadores Personales — Agenda Online',
        description: 'Sistema de turnos para entrenadores personales. Sesiones individuales y grupales con cobro automático. Empezá gratis.',
        keywords: ['turnos entrenador personal online', 'agenda personal trainer', 'sistema reservas entrenador', 'software personal trainer argentina'],
      },
      pill: '🏃 Entrenadores Personales',
      heroTitle: 'Tu agenda de entrenador',
      heroSubtitle: 'siempre completa.',
      painPoints: [
        { title: 'Clientes que cancelan', desc: 'Reservan sesión y cancelan 1 hora antes. Perdés el horario y no podés llenarlo.' },
        { title: 'Cobro informal', desc: 'Transferencias que no llegan, efectivo que no tenés cambio. Cobrar es un dolor de cabeza.' },
        { title: 'Sin estructura', desc: 'Horarios en la cabeza, clientes por WhatsApp, cobros por Mercado Pago manual. Nada profesional.' },
      ],
      capabilities: [
        { icon: 'CalendarCheck', title: 'Agenda profesional', desc: 'Tus clientes ven tu disponibilidad y reservan su sesión. Sin mensajes ida y vuelta.' },
        { icon: 'CreditCard', title: 'Cobro automático', desc: 'El cliente paga al reservar. Sin transferencias manuales, sin esperar pagos.' },
        { icon: 'Timer', title: 'Sesiones personalizadas', desc: 'Individual 60 min, grupal 45 min, evaluación 90 min. Cada tipo con su precio.' },
        { icon: 'Users', title: 'Ficha de alumno', desc: 'Objetivos, lesiones, nivel de fitness, progreso. Todo registrado.' },
        { icon: 'Bell', title: 'Recordatorios', desc: 'Tu alumno recibe un WhatsApp antes de la sesión. Menos cancelaciones de último momento.' },
        { icon: 'Globe', title: 'Link profesional', desc: 'Compartí tu link en redes y Google. Conseguí nuevos alumnos sin esfuerzo.' },
      ],
      subIndustries: ['Entrenamiento individual', 'Grupos reducidos', 'Entrenamiento online', 'Evaluaciones físicas', 'Planes de entrenamiento', 'Preparación deportiva'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Antes cobraba con transferencias y siempre faltaba alguien. Ahora pagan al reservar y no tengo que perseguir a nadie.', name: 'Franco Mendoza', role: 'Personal trainer', business: 'Franco Fitness', image: 'https://randomuser.me/api/portraits/men/53.jpg' },
        { quote: 'Mi agenda se llena sola. Los alumnos reservan desde Instagram y yo me enfoco en entrenar.', name: 'Agustina Ponce', role: 'Entrenadora', business: 'Agus Training', image: 'https://randomuser.me/api/portraits/women/62.jpg' },
        { quote: 'Las cancelaciones de último momento bajaron un 80%. La seña hace que se comprometan.', name: 'Diego Carrizo', role: 'Personal trainer', business: 'DC Entrenamiento', image: 'https://randomuser.me/api/portraits/men/54.jpg' },
      ],
      faqs: [
        { q: '¿Puedo ofrecer sesiones individuales y grupales?', a: 'Sí. Cada tipo como servicio independiente con su duración, precio y cupo.' },
        { q: '¿Funciona para entrenar en distintos lugares?', a: 'Sí. Podés tener horarios en el gimnasio, al aire libre o en casa del cliente.' },
        { q: '¿Puedo vender paquetes de sesiones?', a: 'Sí. Paquetes de 8, 12 o 16 sesiones a precio especial.' },
        { q: '¿Mis alumnos pueden elegir el tipo de sesión?', a: 'Sí. Ven la lista de servicios con descripción y precio y eligen la que quieren.' },
        { q: '¿El pago va directo a mi cuenta?', a: 'Sí. Se cobra por Mercado Pago y la plata va directo a tu cuenta bancaria.' },
        { q: '¿Puedo llevar registro del progreso?', a: 'Sí. En la ficha del alumno anotás peso, medidas, marcas y observaciones de cada sesión.' },
      ],
      cta: { headline: 'Profesionalizá tu servicio', subtitle: 'de entrenamiento.', description: 'Creá tu cuenta gratis, cargá tus servicios y que tus alumnos reserven y paguen solos.' },
    },

    'salas-de-ensayo': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Salas de Ensayo — Reservas Online y Cobro Automático',
        description: 'Sistema de reservas para salas de ensayo musical. Bloques horarios, cobro automático y gestión de salas. Empezá gratis.',
        keywords: ['reservas sala ensayo online', 'turnos sala ensayo', 'alquiler sala ensayo', 'sistema reservas sala música', 'software sala ensayo argentina'],
      },
      pill: '🎵 Salas de Ensayo',
      heroTitle: 'Tus salas de ensayo',
      heroSubtitle: 'siempre reservadas.',
      painPoints: [
        { title: 'Bandas que no aparecen', desc: 'Reservan 2 horas de sala y no vienen. Perdés el bloque más rentable del día.' },
        { title: 'Gestión manual', desc: 'Cuaderno de reservas, llamadas telefónicas, mensajes de WhatsApp. Un caos para coordinar.' },
        { title: 'Múltiples salas y equipamiento', desc: 'Sala con batería, sala con amplis, sala premium. Cada una con su precio. Difícil de gestionar.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de salas', desc: 'Sala A, B, C. Cada una con su equipamiento, capacidad y precio por hora.' },
        { icon: 'CreditCard', title: 'Seña por reserva', desc: 'La banda paga al reservar. Si no viene, la seña queda. Protegé tus horarios.' },
        { icon: 'Timer', title: 'Bloques horarios', desc: 'Mínimo 1 hora, máximo 4 horas. La banda elige cuánto tiempo necesita.' },
        { icon: 'CalendarCheck', title: 'Reservas 24/7', desc: 'Las bandas reservan a cualquier hora. Sin esperar a que abra la sala.' },
        { icon: 'Globe', title: 'Presencia online', desc: 'Que te encuentren en Google. Un link profesional para compartir en redes y grupos.' },
        { icon: 'LayoutDashboard', title: 'Ocupación y facturación', desc: 'Sabé qué sala factura más, qué horarios están vacíos y dónde tenés oportunidad.' },
      ],
      subIndustries: ['Ensayo de bandas', 'Práctica individual', 'Clases de música', 'Grabación básica', 'Producción', 'Jam sessions'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Tengo 3 salas y antes vivía pegado al teléfono. Ahora las bandas reservan solas y pagan al instante.', name: 'Julián Morales', role: 'Dueño', business: 'Studio 23 Salas', image: 'https://randomuser.me/api/portraits/men/55.jpg' },
        { quote: 'La seña eliminó los plantones. Las bandas se comprometen cuando pagan por adelantado.', name: 'Rodrigo Sáenz', role: 'Gerente', business: 'Rock & Roll Salas', image: 'https://randomuser.me/api/portraits/men/56.jpg' },
        { quote: 'La ocupación subió un 35% porque ahora las bandas pueden reservar a las 2am cuando salen del show.', name: 'Natalia Crespo', role: 'Dueña', business: 'Sound Factory', image: 'https://randomuser.me/api/portraits/women/63.jpg' },
      ],
      faqs: [
        { q: '¿Puedo diferenciar salas por equipamiento?', a: 'Sí. Sala con batería, sala con amplis, sala premium. Cada una con su descripción, precio y fotos.' },
        { q: '¿Las bandas pueden elegir cuántas horas?', a: 'Sí. Configurás bloques de 1, 2, 3 o 4 horas. La banda elige lo que necesita.' },
        { q: '¿Funciona para clases de música también?', a: 'Sí. Creás un servicio de clase con su duración y precio, asignado a una sala.' },
        { q: '¿Puedo tener precios por hora diferenciados?', a: 'Sí. Hora diurna, nocturna, fin de semana. Todo configurable por sala.' },
        { q: '¿Se cobra la seña o el total?', a: 'Vos decidís. Podés cobrar solo seña o el total del bloque al momento de reservar.' },
        { q: '¿Puedo agregar servicios extra?', a: 'Sí. Ingeniero de sonido, alquiler de instrumentos, grabación. Como servicios adicionales.' },
      ],
      cta: { headline: 'Llenà tus salas', subtitle: 'de ensayo.', description: 'Creá tu cuenta gratis, cargá tus salas y empezá a recibir reservas con cobro automático.' },
    },

    'estudios-de-grabacion': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Estudios de Grabación — Reservas de Sesiones Online',
        description: 'Sistema de reservas para estudios de grabación. Sesiones de grabación, mezcla y producción con cobro automático. Empezá gratis.',
        keywords: ['reservas estudio grabación online', 'turnos estudio grabación', 'alquiler estudio grabación', 'sistema reservas estudio música', 'software estudio grabación argentina'],
      },
      pill: '🎙️ Estudios de Grabación',
      heroTitle: 'Tu estudio de grabación',
      heroSubtitle: 'con sesiones siempre agendadas.',
      painPoints: [
        { title: 'Sesiones costosas canceladas', desc: 'Un día de grabación vale mucho. Si el artista cancela, perdés el día y el ingeniero.' },
        { title: 'Coordinación compleja', desc: 'Artista, productor, ingeniero, sala. Coordinar a todos para el mismo día es un rompecabezas.' },
        { title: 'Sin presencia online', desc: 'Artistas emergentes buscan estudios en Google y redes. Si no estás, no existís.' },
      ],
      capabilities: [
        { icon: 'Building2', title: 'Gestión de salas', desc: 'Sala de grabación, sala de mezcla, cabina de voz. Cada una con su equipamiento y tarifa.' },
        { icon: 'CreditCard', title: 'Seña por sesión', desc: 'El artista paga una seña al reservar. Protegé tu inversión en tiempo y equipo.' },
        { icon: 'Timer', title: 'Sesiones flexibles', desc: 'Bloques de 2, 4, 8 o 12 horas. Grabación, mezcla o mastering con duración a medida.' },
        { icon: 'Users', title: 'Gestión de ingenieros', desc: 'Cada ingeniero con su disponibilidad y especialidad. El artista elige con quién trabajar.' },
        { icon: 'Globe', title: 'Presencia profesional', desc: 'Link de reservas para tu web, Spotify y redes. Que los artistas te encuentren y reserven.' },
        { icon: 'CalendarCheck', title: 'Calendario de estudio', desc: 'Visualizá la ocupación del estudio: qué salas están libres, cuándo hay ventanas.' },
      ],
      subIndustries: ['Grabación', 'Mezcla', 'Mastering', 'Producción musical', 'Podcast', 'Voiceover', 'Doblaje'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Artistas me reservan sesiones de grabación desde Instagram. Es mucho más profesional y organizado.', name: 'Pablo Estrada', role: 'Productor', business: 'Estrada Records Studio', image: 'https://randomuser.me/api/portraits/men/57.jpg' },
        { quote: 'La seña me salvó de varias cancelaciones costosas. Ahora el artista se compromete con plata.', name: 'Lucas Villalba', role: 'Ingeniero', business: 'LV Audio Studio', image: 'https://randomuser.me/api/portraits/men/58.jpg' },
        { quote: 'Gestiono 2 salas y 3 ingenieros. TurnoLink me permite coordinar todo sin drama.', name: 'Camila Roldán', role: 'Directora', business: 'Sonic Studio BA', image: 'https://randomuser.me/api/portraits/women/64.jpg' },
      ],
      faqs: [
        { q: '¿Puedo ofrecer sesiones de distinta duración?', a: 'Sí. Grabación medio día, día completo, hora suelta. Cada formato con su precio.' },
        { q: '¿Funciona para podcasting?', a: 'Sí. Creás un servicio de sesión podcast con su duración y precio. Ideal para estudios versátiles.' },
        { q: '¿Los artistas pueden elegir ingeniero?', a: 'Sí. Cada ingeniero tiene su perfil con disponibilidad. El artista elige con quién trabajar.' },
        { q: '¿Puedo ofrecer servicios extra?', a: 'Sí. Alquiler de micrófonos, backline, catering. Como servicios adicionales al reservar.' },
        { q: '¿La seña se descuenta del total?', a: 'Lo definís vos. Puede ser a cuenta del total o como garantía de reserva.' },
        { q: '¿Puedo gestionar mezcla y mastering online?', a: 'Sí. Creás servicios remotos donde el artista reserva y sube los archivos.' },
      ],
      cta: { headline: 'Profesionalizá tu estudio', subtitle: 'de grabación.', description: 'Creá tu cuenta gratis, cargá tus salas y servicios. Reservas y cobros automáticos para tu estudio.' },
    },
  },
};

export default deportesConfig;
