import type { NicheConfig } from './types';

const ACCENT = '#F59E0B';
const PARENT_URL = '/mercado';
const PARENT_LABEL = 'Mercado';

const SHARED_PRICING = {
  hasFree: true,
  tiers: [
    {
      name: 'Vitrina',
      price: '$0',
      period: 'para siempre',
      features: ['Catálogo online ilimitado', 'Botón de WhatsApp', 'Link personalizado', 'Hasta 50 productos'],
    },
    {
      name: 'Comercio',
      price: '$9.990',
      period: '/mes',
      popular: true,
      features: ['Todo lo de Vitrina', 'Carrito de compras', 'Gestión de stock', 'Cupones de descuento', 'Variantes de producto', 'Panel de métricas'],
    },
    {
      name: 'Tienda Pro',
      price: '$19.990',
      period: '/mes',
      features: ['Todo lo de Comercio', 'Checkout con Mercado Pago', 'Pedidos ilimitados', 'Reportes avanzados', 'Soporte prioritario'],
    },
  ],
};

const mercadoConfig: NicheConfig = {
  slug: 'mercado',
  label: 'Mercado',
  accent: ACCENT,
  url: PARENT_URL,
  subNiches: {
    'ropa-y-accesorios': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Tiendas de Ropa — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para tiendas de ropa y accesorios. Catálogo con talles, colores y stock en tiempo real. Empezá gratis.',
        keywords: ['tienda ropa online argentina', 'catálogo ropa online', 'vender ropa por internet', 'sistema ventas indumentaria', 'e-commerce ropa argentina'],
      },
      pill: '👗 Ropa y Accesorios',
      heroTitle: 'Tu tienda de ropa con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Ventas solo por Instagram', desc: 'Respondés mensajes uno por uno, pasás precios por DM y perdés ventas cuando no contestás a tiempo.' },
        { title: 'Talles y colores sin control', desc: 'No sabés qué talles quedan de cada prenda. Vendés algo que ya no tenés y quedás mal.' },
        { title: 'Sin presencia profesional', desc: 'Tus competidores ya tienen tienda online con fotos, precios y carrito. Vos seguís con un link en bio.' },
      ],
      capabilities: [
        { icon: 'ShoppingBag', title: 'Catálogo de prendas', desc: 'Fotos, talles, colores, precios. Todo organizado por categoría y temporada.' },
        { icon: 'Package', title: 'Control de stock', desc: 'Stock por talle y color. Cuando se agota, se marca automáticamente como sin stock.' },
        { icon: 'Tag', title: 'Cupones de descuento', desc: 'Creá cupones por temporada, liquidación o para clientes frecuentes.' },
        { icon: 'Smartphone', title: 'Catálogo mobile', desc: 'El 85% de tus clientes te busca desde el celular. Tu catálogo se ve perfecto.' },
        { icon: 'MessageCircle', title: 'Botón de WhatsApp', desc: 'El cliente ve la prenda, elige talle y te escribe directo con el pedido armado.' },
        { icon: 'TrendingUp', title: 'Métricas de venta', desc: 'Qué prendas se venden más, qué talles se agotan primero, cuánto facturás por semana.' },
      ],
      subIndustries: ['Ropa femenina', 'Ropa masculina', 'Accesorios y bijouterie', 'Calzado', 'Ropa infantil', 'Lencería'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Antes perdía ventas porque no contestaba los DM a tiempo. Ahora mi catálogo vende solo, con talles y stock actualizado.', name: 'Valentina Suárez', role: 'Dueña', business: 'Valentina Store', image: 'https://randomuser.me/api/portraits/women/91.jpg' },
        { quote: 'El control de stock por talle me salvó. Ya no vendo prendas que no tengo y mis clientas confían más.', name: 'Romina Acosta', role: 'Fundadora', business: 'Roma Indumentaria', image: 'https://randomuser.me/api/portraits/women/92.jpg' },
        { quote: 'Mis clientas compran desde el celular a cualquier hora. Las ventas crecieron un 50% en dos meses.', name: 'Federico Paz', role: 'Director', business: 'Urban BA', image: 'https://randomuser.me/api/portraits/men/91.jpg' },
      ],
      faqs: [
        { q: '¿Puedo cargar variantes por talle y color?', a: 'Sí. Cada producto puede tener múltiples combinaciones de talle y color, cada una con su stock independiente.' },
        { q: '¿Mis clientes pueden comprar desde el celular?', a: 'Sí. El catálogo es 100% responsive y se ve perfecto en cualquier dispositivo.' },
        { q: '¿Puedo hacer liquidaciones con descuento?', a: 'Sí. Creás cupones de descuento por porcentaje o monto fijo con fecha de vencimiento.' },
        { q: '¿Necesito saber programar?', a: 'No. Cargás tus productos con fotos, precio y talles. En minutos tenés tu tienda online.' },
        { q: '¿Puedo conectar Mercado Pago?', a: 'Sí. Con el plan Tienda Pro tus clientes pagan directo en tu catálogo con tarjeta o transferencia.' },
        { q: '¿Cómo me encuentran los clientes?', a: 'Te damos un link personalizado que podés compartir en redes, WhatsApp y Google.' },
      ],
      cta: { headline: 'Vendé tu ropa', subtitle: 'las 24 horas.', description: 'Creá tu catálogo gratis, cargá tus prendas con talles y colores, y empezá a vender online.' },
    },

    inmobiliarias: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Inmobiliarias — Catálogo de Propiedades Online',
        description: 'Plataforma para inmobiliarias. Catálogo de propiedades con fotos, ubicación y consulta directa por WhatsApp. Empezá gratis.',
        keywords: ['inmobiliaria online argentina', 'catálogo propiedades online', 'sistema inmobiliaria', 'software inmobiliaria argentina', 'publicar propiedades online'],
      },
      pill: '🏠 Inmobiliarias',
      heroTitle: 'Tu inmobiliaria con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Portales caros y saturados', desc: 'Pagás fortunas en ZonaProp y Argenprop pero tus propiedades se pierden entre miles. Sin identidad propia.' },
        { title: 'Consultas por todos lados', desc: 'Te escriben por WhatsApp, email, portales, Instagram. Perdés consultas y no sabés de dónde vienen.' },
        { title: 'Fotos desactualizadas', desc: 'Publicás en 5 plataformas distintas y cuando se alquila algo, tenés que actualizar en todas.' },
      ],
      capabilities: [
        { icon: 'Image', title: 'Fichas de propiedad', desc: 'Fotos HD, planos, ubicación, ambientes, precio y estado. Todo en una ficha profesional.' },
        { icon: 'Search', title: 'Búsqueda por filtros', desc: 'Tus clientes filtran por zona, precio, ambientes y tipo. Encuentran lo que buscan rápido.' },
        { icon: 'MessageCircle', title: 'Consulta por WhatsApp', desc: 'El interesado ve la propiedad y te consulta directo con los datos del inmueble.' },
        { icon: 'Globe', title: 'Tu propio sitio', desc: 'Link profesional con tu marca. Dejá de depender solo de portales de terceros.' },
        { icon: 'Share2', title: 'Compartir en redes', desc: 'Compartí cada propiedad en Instagram, Facebook y WhatsApp con un click.' },
        { icon: 'BarChart', title: 'Propiedades más vistas', desc: 'Sabé cuáles generan más interés, cuántas consultas recibís y de dónde vienen.' },
      ],
      subIndustries: ['Venta de departamentos', 'Alquiler residencial', 'Alquiler temporario', 'Locales comerciales', 'Terrenos y lotes', 'Desarrollos inmobiliarios'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Tener mi propio catálogo de propiedades me diferencia. Los clientes ven todo sin depender de portales.', name: 'Hernán Figueroa', role: 'Broker', business: 'Figueroa Propiedades', image: 'https://randomuser.me/api/portraits/men/92.jpg' },
        { quote: 'Las consultas por WhatsApp llegan con los datos de la propiedad. Ya no pierdo tiempo preguntando qué buscan.', name: 'Andrea Molina', role: 'Dueña', business: 'Molina Inmobiliaria', image: 'https://randomuser.me/api/portraits/women/93.jpg' },
        { quote: 'Actualizo una vez y se refleja en mi catálogo. Antes cambiaba precios en 5 plataformas distintas.', name: 'Carlos Pereyra', role: 'Director', business: 'Pereyra & Asoc.', image: 'https://randomuser.me/api/portraits/men/93.jpg' },
      ],
      faqs: [
        { q: '¿Puedo cargar propiedades en venta y alquiler?', a: 'Sí. Organizás tu catálogo por tipo de operación: venta, alquiler, alquiler temporario.' },
        { q: '¿Se pueden agregar fotos y planos?', a: 'Sí. Múltiples fotos por propiedad con galería profesional y opción de planos.' },
        { q: '¿Los interesados me contactan directo?', a: 'Sí. Botón de WhatsApp en cada ficha con el mensaje pre-armado con los datos del inmueble.' },
        { q: '¿Puedo filtrar por zona y precio?', a: 'Sí. Tus clientes buscan por barrio, rango de precio, cantidad de ambientes y tipo de propiedad.' },
        { q: '¿Reemplaza a los portales inmobiliarios?', a: 'Lo complementa. Tenés tu propio catálogo con tu marca, además de seguir publicando en portales.' },
        { q: '¿Puedo compartir propiedades en redes?', a: 'Sí. Cada propiedad tiene su link individual para compartir en Instagram, Facebook y WhatsApp.' },
      ],
      cta: { headline: 'Tu inmobiliaria online', subtitle: 'con identidad propia.', description: 'Creá tu catálogo gratis, cargá tus propiedades y recibí consultas directas por WhatsApp.' },
    },

    'alimentos-y-bebidas': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Alimentos y Bebidas — Catálogo y Pedidos Online',
        description: 'Plataforma de venta online para almacenes, dietéticas y productores de alimentos. Catálogo con pedidos por WhatsApp. Empezá gratis.',
        keywords: ['vender alimentos online argentina', 'catálogo almacén online', 'pedidos comida online', 'dietética online', 'sistema ventas alimentos'],
      },
      pill: '🍷 Alimentos y Bebidas',
      heroTitle: 'Tu negocio de alimentos con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Lista de precios por WhatsApp', desc: 'Mandás un PDF con 200 productos y el cliente no encuentra lo que busca. Terminás atendiéndolo uno por uno.' },
        { title: 'Pedidos desordenados', desc: 'Te piden por audio, por mensaje, por llamada. Anotás en un cuaderno y a veces se pierde algo.' },
        { title: 'Stock sin actualizar', desc: 'Vendés un producto que ya no tenés. El cliente se frustra y no vuelve.' },
      ],
      capabilities: [
        { icon: 'ShoppingBag', title: 'Catálogo por categoría', desc: 'Bebidas, panificados, conservas, frescos. Organizado para que el cliente encuentre rápido.' },
        { icon: 'Package', title: 'Control de stock', desc: 'Cuando un producto se agota, se oculta automáticamente. Sin vender lo que no tenés.' },
        { icon: 'CreditCard', title: 'Carrito de pedidos', desc: 'El cliente arma su pedido, elige cantidad y te llega todo organizado.' },
        { icon: 'MessageCircle', title: 'Pedido por WhatsApp', desc: 'El cliente confirma el pedido y te llega un mensaje con todo el detalle.' },
        { icon: 'Tag', title: 'Ofertas y combos', desc: 'Creá combos, descuentos por cantidad y ofertas semanales para tus clientes.' },
        { icon: 'TrendingUp', title: 'Productos más vendidos', desc: 'Sabé qué productos salen más, cuántos pedidos recibís y cuánto facturás.' },
      ],
      subIndustries: ['Almacén natural', 'Dietética', 'Vinoteca', 'Fiambrería', 'Pastelería', 'Productores artesanales'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Pasé de mandar un PDF con precios a tener un catálogo profesional. Los pedidos se triplicaron en un mes.', name: 'Gabriela Ruiz', role: 'Dueña', business: 'Almacén Natural GR', image: 'https://randomuser.me/api/portraits/women/94.jpg' },
        { quote: 'Los clientes arman su pedido solos y me llega por WhatsApp bien organizado. Cero confusión.', name: 'Martín Ledesma', role: 'Dueño', business: 'Vinoteca del Sur', image: 'https://randomuser.me/api/portraits/men/94.jpg' },
        { quote: 'Las ofertas semanales me generan pedidos nuevos cada semana. Mis clientes se acostumbraron a mirar el catálogo.', name: 'Soledad Navarro', role: 'Fundadora', business: 'Dulce Navarro', image: 'https://randomuser.me/api/portraits/women/95.jpg' },
      ],
      faqs: [
        { q: '¿Puedo organizar productos por categoría?', a: 'Sí. Creás categorías como bebidas, frescos, conservas y organizás tu catálogo como quieras.' },
        { q: '¿Los clientes pueden armar un pedido?', a: 'Sí. Con el plan Comercio tienen carrito de compras para armar su pedido completo.' },
        { q: '¿Se actualiza el stock automáticamente?', a: 'Sí. Cuando un producto se agota, deja de mostrarse. Sin vender lo que no tenés.' },
        { q: '¿Puedo hacer ofertas semanales?', a: 'Sí. Creás cupones de descuento y ofertas con fecha de inicio y vencimiento.' },
        { q: '¿Funciona para delivery?', a: 'Sí. El cliente arma su pedido online y vos coordinás el envío o retiro en local.' },
        { q: '¿Puedo vender por peso?', a: 'Sí. Configurás productos por unidad, por kilo o por fracción según tu necesidad.' },
      ],
      cta: { headline: 'Vendé tus productos', subtitle: 'sin complicaciones.', description: 'Creá tu catálogo gratis, cargá tus productos y empezá a recibir pedidos organizados.' },
    },

    cosmeticos: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Cosméticos — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para marcas de cosméticos y belleza. Catálogo con variantes, stock y pedidos. Empezá gratis.',
        keywords: ['vender cosméticos online argentina', 'catálogo cosméticos online', 'tienda belleza online', 'sistema ventas cosméticos', 'e-commerce belleza argentina'],
      },
      pill: '💄 Cosméticos',
      heroTitle: 'Tu marca de cosméticos con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Catálogo en PDF o Instagram', desc: 'Tus productos se pierden en un feed infinito. Las clientas preguntan precios uno por uno por DM.' },
        { title: 'Variantes imposibles de gestionar', desc: 'Cada producto tiene 5 tonos. Controlás stock de cada tono en una planilla de Excel y siempre hay errores.' },
        { title: 'Revendedoras sin herramienta', desc: 'Tus revendedoras necesitan un catálogo profesional para mostrar y no tenés cómo dárselo.' },
      ],
      capabilities: [
        { icon: 'Palette', title: 'Variantes por tono', desc: 'Base clara, media, oscura. Cada producto con sus tonos, colores y presentaciones.' },
        { icon: 'Image', title: 'Fotos profesionales', desc: 'Galería con múltiples fotos por producto. Mostrá texturas, swatches y antes/después.' },
        { icon: 'Package', title: 'Stock por variante', desc: 'Stock independiente por tono y tamaño. Nunca más vendés lo que no tenés.' },
        { icon: 'Share2', title: 'Link para revendedoras', desc: 'Compartí el catálogo con tus revendedoras. Ellas muestran y vos controlás.' },
        { icon: 'Tag', title: 'Kits y combos', desc: 'Armá kits de temporada, combos de regalo y sets con descuento.' },
        { icon: 'Star', title: 'Productos destacados', desc: 'Destacá lanzamientos y best sellers para que los clientes los vean primero.' },
      ],
      subIndustries: ['Maquillaje', 'Skincare', 'Perfumería', 'Cosmética natural', 'Cuidado capilar', 'Uñas y nail art'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Mis revendedoras tienen un catálogo profesional para mostrar. Las ventas mayoristas crecieron un 70%.', name: 'Luciana Campos', role: 'Fundadora', business: 'Lux Cosmetics', image: 'https://randomuser.me/api/portraits/women/96.jpg' },
        { quote: 'Cada base tiene 8 tonos y ahora controlo el stock de cada uno sin planillas. Todo automático.', name: 'Mariana Torres', role: 'Dueña', business: 'MT Beauty', image: 'https://randomuser.me/api/portraits/women/97.jpg' },
        { quote: 'El catálogo con fotos profesionales elevó la percepción de mi marca. Las clientas compran más seguras.', name: 'Nicolás Gómez', role: 'Director', business: 'NG Cosméticos', image: 'https://randomuser.me/api/portraits/men/95.jpg' },
      ],
      faqs: [
        { q: '¿Puedo cargar variantes por tono y tamaño?', a: 'Sí. Cada producto puede tener múltiples variantes con stock y precio independiente.' },
        { q: '¿Mis revendedoras pueden ver el catálogo?', a: 'Sí. Compartís el link del catálogo y ellas muestran los productos desde su celular.' },
        { q: '¿Puedo armar kits de regalo?', a: 'Sí. Creás combos y kits con descuento como si fueran un producto nuevo.' },
        { q: '¿Se pueden subir varias fotos por producto?', a: 'Sí. Galería de fotos con múltiples imágenes por producto para mostrar texturas y colores.' },
        { q: '¿Funciona para venta mayorista?', a: 'Sí. Podés manejar precios minoristas y usar el catálogo como herramienta para revendedoras.' },
        { q: '¿Puedo destacar productos nuevos?', a: 'Sí. Los productos destacados aparecen primero en el catálogo para mayor visibilidad.' },
      ],
      cta: { headline: 'Vendé tus cosméticos', subtitle: 'con catálogo profesional.', description: 'Creá tu catálogo gratis, cargá tus productos con variantes y empezá a vender online.' },
    },

    artesanias: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Artesanías — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para artesanos. Catálogo con piezas únicas, pedidos personalizados y ventas por WhatsApp. Empezá gratis.',
        keywords: ['vender artesanías online argentina', 'catálogo artesanías', 'tienda artesanal online', 'artesanos venta online', 'e-commerce artesanías'],
      },
      pill: '🎨 Artesanías',
      heroTitle: 'Tus artesanías con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Solo vendés en ferias', desc: 'Dependés de ferias los fines de semana. Si llueve o no hay feria, no vendés.' },
        { title: 'Piezas únicas sin catálogo', desc: 'Cada pieza es diferente y no tenés dónde mostrarlas todas con sus detalles y precios.' },
        { title: 'Pedidos personalizados por chat', desc: 'Te piden algo especial por WhatsApp, negociás ida y vuelta y a veces no cierra. Perdés horas.' },
      ],
      capabilities: [
        { icon: 'Image', title: 'Galería de piezas', desc: 'Fotos detalladas de cada pieza: material, medidas, técnica y proceso de creación.' },
        { icon: 'Star', title: 'Piezas destacadas', desc: 'Mostrá tus mejores creaciones primero. Lo nuevo y lo más vendido en un lugar visible.' },
        { icon: 'MessageCircle', title: 'Pedidos personalizados', desc: 'El cliente te consulta por WhatsApp con la pieza de referencia ya seleccionada.' },
        { icon: 'Globe', title: 'Tu tienda propia', desc: 'Link profesional para compartir en ferias, redes y con cada persona que te pregunte.' },
        { icon: 'ShoppingBag', title: 'Categorías por técnica', desc: 'Cerámica, tejido, madera, cuero. Organizá tu catálogo por material o técnica.' },
        { icon: 'Share2', title: 'Compartir en redes', desc: 'Cada pieza tiene su link. Compartí en Instagram y WhatsApp con un toque.' },
      ],
      subIndustries: ['Cerámica artesanal', 'Tejidos y textiles', 'Trabajo en madera', 'Cuero y marroquinería', 'Velas y sahumerios', 'Jabones artesanales'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Vendía solo en ferias. Ahora vendo toda la semana con mi catálogo online. Es otro ingreso constante.', name: 'Patricia Herrera', role: 'Artesana', business: 'Manos del Sur', image: 'https://randomuser.me/api/portraits/women/98.jpg' },
        { quote: 'Mis piezas de cerámica se ven hermosas en el catálogo. Los clientes eligen y me escriben directo.', name: 'Jorge Villalba', role: 'Ceramista', business: 'Tierra Viva Cerámica', image: 'https://randomuser.me/api/portraits/men/96.jpg' },
        { quote: 'En la feria reparto tarjetas con mi link. La gente entra después y me hace pedidos. Funciona increíble.', name: 'Marina Sosa', role: 'Fundadora', business: 'Marina Tejidos', image: 'https://randomuser.me/api/portraits/women/99.jpg' },
      ],
      faqs: [
        { q: '¿Funciona para piezas únicas?', a: 'Sí. Cada pieza puede cargarse como producto individual con stock 1. Cuando se vende, desaparece.' },
        { q: '¿Puedo recibir pedidos personalizados?', a: 'Sí. El cliente ve tu catálogo como referencia y te contacta por WhatsApp para encargar algo especial.' },
        { q: '¿Puedo organizar por técnica o material?', a: 'Sí. Creás categorías como cerámica, tejido, madera y organizás tu catálogo a gusto.' },
        { q: '¿Sirve para complementar las ferias?', a: 'Perfecto. Repartís tu link en la feria y los clientes siguen comprando después desde su casa.' },
        { q: '¿Puedo mostrar el proceso de creación?', a: 'Sí. Subís múltiples fotos por pieza mostrando materiales, proceso y resultado final.' },
        { q: '¿Es fácil de usar?', a: 'Sí. Sacás fotos, cargás nombre, precio y descripción. En minutos tenés tu catálogo listo.' },
      ],
      cta: { headline: 'Vendé tus artesanías', subtitle: 'más allá de la feria.', description: 'Creá tu catálogo gratis, subí tus piezas y vendé toda la semana desde tu celular.' },
    },

    joyeria: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Joyería — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para joyerías y bijouterie. Catálogo profesional con fotos, materiales y precios. Empezá gratis.',
        keywords: ['vender joyas online argentina', 'catálogo joyería online', 'tienda bijouterie online', 'e-commerce joyería', 'vender bijouterie por internet'],
      },
      pill: '💍 Joyería',
      heroTitle: 'Tu joyería con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Fotos sin contexto', desc: 'Subís fotos a Instagram pero nadie sabe el precio, el material ni si está disponible. Preguntan todo por DM.' },
        { title: 'Inventario en una planilla', desc: 'Tenés 200 piezas con distintos materiales y piedras. Controlar stock en Excel es un caos.' },
        { title: 'Sin diferenciación online', desc: 'Tu competencia tiene catálogo profesional con materiales y certificados. Vos tenés un feed de Instagram.' },
      ],
      capabilities: [
        { icon: 'Star', title: 'Fichas de producto', desc: 'Material, peso, piedras, certificación. Cada joya con su ficha técnica profesional.' },
        { icon: 'Image', title: 'Galería premium', desc: 'Múltiples fotos por pieza: detalle, puesta, caja. Mostrá la calidad de tu trabajo.' },
        { icon: 'Package', title: 'Stock en tiempo real', desc: 'Cuando una pieza se vende, se actualiza automáticamente. Sin vender lo que no tenés.' },
        { icon: 'Tag', title: 'Colecciones', desc: 'Organizá por colección, temporada o línea. Anillos, aros, collares, pulseras.' },
        { icon: 'CreditCard', title: 'Pagos seguros', desc: 'Checkout con Mercado Pago. Tus clientes pagan con tarjeta o transferencia.' },
        { icon: 'MessageCircle', title: 'Consulta directa', desc: 'El cliente ve la pieza con todos sus detalles y te escribe con el pedido listo.' },
      ],
      subIndustries: ['Joyería en plata', 'Joyería en oro', 'Bijouterie de autor', 'Piedras naturales', 'Joyería personalizada'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Mi catálogo muestra cada joya con material, peso y certificación. Las clientas compran con confianza.', name: 'Carolina Méndez', role: 'Diseñadora', business: 'CM Joyería de Autor', image: 'https://randomuser.me/api/portraits/women/100.jpg' },
        { quote: 'Antes contestaba 50 DM por día preguntando precios. Ahora todo está en el catálogo y me escriben para comprar.', name: 'Sebastián Ríos', role: 'Dueño', business: 'Ríos Platería', image: 'https://randomuser.me/api/portraits/men/97.jpg' },
        { quote: 'Las colecciones organizadas por temporada me permiten lanzar nuevas líneas con un link y listo.', name: 'Florencia Díaz', role: 'Fundadora', business: 'Flor Bijoux', image: 'https://randomuser.me/api/portraits/women/101.jpg' },
      ],
      faqs: [
        { q: '¿Puedo detallar materiales y piedras?', a: 'Sí. Cada pieza tiene su ficha técnica con material, peso, piedras y certificación si corresponde.' },
        { q: '¿Funciona para bijouterie y joyería fina?', a: 'Sí. Creás categorías separadas para cada línea con precios y fichas técnicas distintas.' },
        { q: '¿Las fotos se ven en alta calidad?', a: 'Sí. Galería con zoom y múltiples ángulos para que el cliente vea cada detalle.' },
        { q: '¿Puedo organizar por colección?', a: 'Sí. Colecciones por temporada, línea o material. El cliente navega fácil entre ellas.' },
        { q: '¿Los clientes pueden pagar online?', a: 'Sí. Con el plan Tienda Pro, checkout integrado con Mercado Pago.' },
        { q: '¿Puedo hacer piezas personalizadas por encargo?', a: 'Sí. El cliente ve tu catálogo como referencia y te contacta para encargar algo a medida.' },
      ],
      cta: { headline: 'Mostrá tus joyas', subtitle: 'con catálogo profesional.', description: 'Creá tu catálogo gratis, subí tus piezas con fichas técnicas y vendé online.' },
    },

    electronica: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Electrónica — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para tiendas de electrónica y tecnología. Catálogo con specs, stock y comparación. Empezá gratis.',
        keywords: ['vender electrónica online argentina', 'catálogo tecnología online', 'tienda electrónica online', 'e-commerce electrónica', 'vender celulares online'],
      },
      pill: '📱 Electrónica',
      heroTitle: 'Tu tienda de electrónica con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Precios que cambian todo el tiempo', desc: 'El dólar sube y tenés que actualizar 500 productos. En una planilla tardás un día entero.' },
        { title: 'Specs en el aire', desc: 'El cliente pregunta por RAM, almacenamiento, procesador. Buscás en la caja o googleás cada vez.' },
        { title: 'Competencia con tiendas grandes', desc: 'MercadoLibre y las grandes cadenas tienen catálogo online. Vos tenés un local y WhatsApp.' },
      ],
      capabilities: [
        { icon: 'LayoutDashboard', title: 'Fichas técnicas', desc: 'Procesador, RAM, pantalla, batería. Especificaciones detalladas de cada producto.' },
        { icon: 'Package', title: 'Stock en tiempo real', desc: 'Cuando vendés una unidad, el stock se actualiza. Sin vender lo que no tenés.' },
        { icon: 'Tag', title: 'Precios actualizables', desc: 'Actualizá precios masivamente en minutos. Sin recorrer producto por producto.' },
        { icon: 'Search', title: 'Búsqueda por spec', desc: 'Tus clientes buscan por marca, rango de precio o categoría. Encuentran rápido.' },
        { icon: 'CreditCard', title: 'Cobro con Mercado Pago', desc: 'Tarjeta, transferencia o cuotas. El cliente paga como prefiera.' },
        { icon: 'Smartphone', title: 'Catálogo mobile', desc: 'Tus clientes comparan productos desde el celular. Todo rápido y claro.' },
      ],
      subIndustries: ['Celulares y accesorios', 'Computación', 'Audio y parlantes', 'Gaming', 'Componentes y repuestos', 'Electrodomésticos pequeños'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Antes actualizaba precios todo el día. Ahora los cambio masivamente en minutos y mi catálogo está siempre al día.', name: 'Diego Fernández', role: 'Dueño', business: 'TecnoShop DF', image: 'https://randomuser.me/api/portraits/men/98.jpg' },
        { quote: 'Las fichas técnicas hacen que el cliente llegue informado. Me preguntan para comprar, no para averiguar specs.', name: 'Analía Quiroga', role: 'Gerente', business: 'QuirogaTech', image: 'https://randomuser.me/api/portraits/women/102.jpg' },
        { quote: 'Compito con las tiendas grandes porque tengo catálogo profesional y atención personalizada. Gano por los dos lados.', name: 'Ramiro Bustos', role: 'Fundador', business: 'RB Electrónica', image: 'https://randomuser.me/api/portraits/men/99.jpg' },
      ],
      faqs: [
        { q: '¿Puedo cargar especificaciones técnicas?', a: 'Sí. Cada producto tiene campos para procesador, RAM, pantalla, batería y más.' },
        { q: '¿Se pueden actualizar precios masivamente?', a: 'Sí. Actualizá precios de todos los productos de una categoría en minutos.' },
        { q: '¿Funciona con cuotas?', a: 'Sí. Con Mercado Pago tus clientes pagan en cuotas con tarjeta de crédito.' },
        { q: '¿Los clientes pueden comparar productos?', a: 'Sí. Las fichas técnicas permiten que comparen especificaciones entre productos similares.' },
        { q: '¿Puedo organizar por marca?', a: 'Sí. Categorías por marca, tipo de producto o rango de precio.' },
        { q: '¿Funciona para servicio técnico también?', a: 'TurnoLink está pensado para venta de productos. Para turnos de servicio técnico podés usar nuestra solución de reservas.' },
      ],
      cta: { headline: 'Vendé tecnología', subtitle: 'con catálogo profesional.', description: 'Creá tu catálogo gratis, cargá tus productos con fichas técnicas y empezá a vender online.' },
    },

    decoracion: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Decoración y Hogar — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para tiendas de decoración y hogar. Catálogo visual con ambientaciones y pedidos. Empezá gratis.',
        keywords: ['vender decoración online argentina', 'catálogo deco online', 'tienda hogar online', 'e-commerce decoración', 'vender deco por internet'],
      },
      pill: '🏡 Decoración',
      heroTitle: 'Tu tienda de deco con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Fotos que no venden', desc: 'Subís fotos de productos sueltos pero el cliente no se imagina cómo quedan en su casa.' },
        { title: 'Medidas y materiales por WhatsApp', desc: 'Cada cliente pregunta medidas, material, color. Respondés lo mismo 20 veces al día.' },
        { title: 'Productos pesados sin envío claro', desc: 'El cliente quiere comprar pero no sabe si hacés envío, cuánto sale ni si entra por la puerta.' },
      ],
      capabilities: [
        { icon: 'Image', title: 'Fotos ambientadas', desc: 'Mostrá cada producto en contexto: living, dormitorio, cocina. El cliente se imagina cómo queda.' },
        { icon: 'Package', title: 'Fichas con medidas', desc: 'Alto, ancho, profundidad, peso, material. Todo detallado para que no pregunten.' },
        { icon: 'Palette', title: 'Variantes de color', desc: 'Cada producto en sus colores disponibles con foto de cada variante.' },
        { icon: 'ShoppingBag', title: 'Ambientes como categoría', desc: 'Living, dormitorio, baño, cocina, exterior. El cliente busca por espacio del hogar.' },
        { icon: 'MessageCircle', title: 'Consulta con contexto', desc: 'El cliente te escribe con el producto seleccionado, las medidas y el color que le interesa.' },
        { icon: 'Star', title: 'Productos destacados', desc: 'Lo nuevo, lo más vendido y las ofertas de temporada siempre visibles.' },
      ],
      subIndustries: ['Muebles', 'Iluminación', 'Textiles para el hogar', 'Bazar y vajilla', 'Plantas y macetas', 'Cuadros y arte decorativo'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Las fotos ambientadas cambiaron todo. Los clientes ven cómo queda el producto en un living real y compran seguros.', name: 'Cecilia Varela', role: 'Dueña', business: 'Deco Varela', image: 'https://randomuser.me/api/portraits/women/103.jpg' },
        { quote: 'Ya no contesto medidas por WhatsApp. Todo está en la ficha del producto. Me consultan solo para comprar.', name: 'Leandro Páez', role: 'Fundador', business: 'Casa Páez', image: 'https://randomuser.me/api/portraits/men/100.jpg' },
        { quote: 'Organicé mi catálogo por ambiente y las ventas subieron. Los clientes encuentran lo que buscan mucho más fácil.', name: 'Natalia Ocampo', role: 'Directora', business: 'Nativa Deco', image: 'https://randomuser.me/api/portraits/women/104.jpg' },
      ],
      faqs: [
        { q: '¿Puedo mostrar productos ambientados?', a: 'Sí. Subís fotos del producto en contexto para que el cliente vea cómo queda en su espacio.' },
        { q: '¿Se pueden cargar medidas detalladas?', a: 'Sí. Alto, ancho, profundidad, peso y material en la ficha de cada producto.' },
        { q: '¿Funciona para muebles grandes?', a: 'Sí. Fichas con medidas exactas y opción de coordinar envío o retiro por WhatsApp.' },
        { q: '¿Puedo organizar por ambiente?', a: 'Sí. Living, dormitorio, baño, cocina. El cliente busca por el espacio que quiere decorar.' },
        { q: '¿Los clientes ven los colores disponibles?', a: 'Sí. Cada variante de color con su foto para que elijan con seguridad.' },
        { q: '¿Puedo hacer ofertas de temporada?', a: 'Sí. Cupones de descuento y productos destacados para promociones de temporada.' },
      ],
      cta: { headline: 'Vendé decoración', subtitle: 'con fotos que enamoran.', description: 'Creá tu catálogo gratis, subí fotos ambientadas de tus productos y empezá a vender online.' },
    },

    'productos-naturales': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Productos Naturales — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para tiendas de productos naturales y orgánicos. Catálogo con ingredientes y beneficios. Empezá gratis.',
        keywords: ['vender productos naturales online argentina', 'catálogo productos orgánicos', 'tienda natural online', 'e-commerce productos naturales', 'dietética online'],
      },
      pill: '🌿 Productos Naturales',
      heroTitle: 'Tu tienda natural con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Clientes con muchas dudas', desc: 'Cada cliente pregunta ingredientes, origen, si es vegano, si es libre de gluten. Respondés mil veces lo mismo.' },
        { title: 'Competencia con supermercados', desc: 'Las cadenas grandes ahora venden "natural". Necesitás diferenciarte con información y servicio.' },
        { title: 'Rotación de productos estacional', desc: 'Productos que se cosechan por temporada, stock que varía. Sin sistema, es un desorden.' },
      ],
      capabilities: [
        { icon: 'Search', title: 'Filtros especiales', desc: 'Vegano, sin gluten, orgánico, sin TACC. Tus clientes filtran por necesidad alimentaria.' },
        { icon: 'ShoppingBag', title: 'Fichas con ingredientes', desc: 'Ingredientes, origen, modo de uso, beneficios. Toda la info que tu cliente necesita.' },
        { icon: 'Package', title: 'Stock estacional', desc: 'Productos de temporada que se agregan y quitan fácilmente según disponibilidad.' },
        { icon: 'Tag', title: 'Sellos y certificaciones', desc: 'Orgánico, agroecológico, comercio justo. Los sellos dan confianza al comprador.' },
        { icon: 'MessageCircle', title: 'Asesoramiento por WhatsApp', desc: 'El cliente te consulta con el producto seleccionado y vos le asesorás con contexto.' },
        { icon: 'TrendingUp', title: 'Productos más buscados', desc: 'Sabé qué buscan tus clientes, qué productos generan más consultas y cuáles se venden más.' },
      ],
      subIndustries: ['Herboristería', 'Productos orgánicos', 'Suplementos naturales', 'Cosmética natural', 'Alimentos sin TACC', 'Aceites esenciales'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Los filtros por "vegano" y "sin gluten" ahorraron miles de consultas. Los clientes encuentran solos lo que necesitan.', name: 'Agustina Prado', role: 'Dueña', business: 'Raíces Naturales', image: 'https://randomuser.me/api/portraits/women/105.jpg' },
        { quote: 'Las fichas con ingredientes y origen generan confianza. Mis clientes compran más seguras que en un supermercado.', name: 'Tomás Medina', role: 'Fundador', business: 'Verde Medina', image: 'https://randomuser.me/api/portraits/men/101.jpg' },
        { quote: 'Manejo productos de temporada con facilidad. Los agrego cuando llegan y los saco cuando se agotan.', name: 'Clara Ibáñez', role: 'Gerente', business: 'Almacén Orgánico CI', image: 'https://randomuser.me/api/portraits/women/106.jpg' },
      ],
      faqs: [
        { q: '¿Puedo filtrar por tipo de alimentación?', a: 'Sí. Vegano, sin gluten, sin TACC, orgánico. Tus clientes encuentran lo que necesitan rápido.' },
        { q: '¿Se pueden detallar ingredientes y origen?', a: 'Sí. Cada producto con sus ingredientes, origen, modo de uso y beneficios.' },
        { q: '¿Funciona para productos a granel?', a: 'Sí. Configurás productos por peso (100g, 250g, 500g, 1kg) con precios distintos.' },
        { q: '¿Puedo mostrar certificaciones?', a: 'Sí. Orgánico, agroecológico, comercio justo. Los sellos aparecen en la ficha del producto.' },
        { q: '¿Funciona para delivery?', a: 'Sí. El cliente arma su pedido y coordinás envío o retiro en local por WhatsApp.' },
        { q: '¿Puedo asesorar a mis clientes?', a: 'Sí. Botón de WhatsApp en cada producto para consultas personalizadas.' },
      ],
      cta: { headline: 'Vendé productos naturales', subtitle: 'con confianza.', description: 'Creá tu catálogo gratis, cargá tus productos con ingredientes y certificaciones, y vendé online.' },
    },

    jugueteria: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Juguetería — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para jugueterías. Catálogo por edad, marca y categoría con pedidos online. Empezá gratis.',
        keywords: ['vender juguetes online argentina', 'catálogo juguetería online', 'tienda juguetes online', 'e-commerce juguetería', 'juguetería venta por internet'],
      },
      pill: '🧸 Juguetería',
      heroTitle: 'Tu juguetería con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Día del Niño y Navidad caóticos', desc: 'Los picos de venta te desbordan. Consultas por WhatsApp que no das abasto. Perdés ventas.' },
        { title: 'Rango de edad sin filtrar', desc: 'Cada padre pregunta "¿qué tenés para un nene de 5 años?". Mostrás todo porque no tenés filtro.' },
        { title: 'Stock desordenado', desc: 'Tenés 500 productos y no sabés cuáles quedan. Vendés algo agotado y el cliente se enoja.' },
      ],
      capabilities: [
        { icon: 'Users', title: 'Filtro por edad', desc: '0-2 años, 3-5, 6-9, 10+. Los padres encuentran el regalo perfecto según la edad.' },
        { icon: 'ShoppingBag', title: 'Categorías claras', desc: 'Didácticos, aire libre, construcción, muñecos, juegos de mesa. Todo organizado.' },
        { icon: 'Package', title: 'Stock actualizado', desc: 'Cada venta descuenta stock. En fechas pico, sabés exactamente qué tenés.' },
        { icon: 'Tag', title: 'Ofertas especiales', desc: 'Día del Niño, Navidad, vuelta a clases. Cupones y descuentos para cada ocasión.' },
        { icon: 'Image', title: 'Fotos atractivas', desc: 'Fotos del juguete armado, en uso y en su caja. El padre ve exactamente qué va a regalar.' },
        { icon: 'CreditCard', title: 'Pagos en cuotas', desc: 'Con Mercado Pago tus clientes pagan en cuotas. Ideal para juguetes de mayor valor.' },
      ],
      subIndustries: ['Juguetes didácticos', 'Juegos de mesa', 'Muñecos y figuras', 'Juguetes de exterior', 'Construcción y STEM', 'Peluches y bebés'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'El Día del Niño fue organizado por primera vez. Los padres armaban pedidos online y yo solo preparaba los paquetes.', name: 'Silvina Montenegro', role: 'Dueña', business: 'Juguetería Mágica', image: 'https://randomuser.me/api/portraits/women/107.jpg' },
        { quote: 'El filtro por edad cambió todo. Los padres encuentran solos el regalo sin preguntarme. Las ventas se aceleraron.', name: 'Pablo Gutiérrez', role: 'Gerente', business: 'ToysBA', image: 'https://randomuser.me/api/portraits/men/102.jpg' },
        { quote: 'Antes perdía ventas en Navidad por no contestar a tiempo. Ahora el catálogo trabaja por mí las 24 horas.', name: 'Lorena Castro', role: 'Fundadora', business: 'Mundo Juguete LC', image: 'https://randomuser.me/api/portraits/women/108.jpg' },
      ],
      faqs: [
        { q: '¿Puedo filtrar por rango de edad?', a: 'Sí. Creás categorías por edad y los padres encuentran juguetes apropiados rápidamente.' },
        { q: '¿Funciona para fechas pico como Día del Niño?', a: 'Perfecto. El catálogo recibe pedidos sin límite y vos preparás los paquetes ordenadamente.' },
        { q: '¿Puedo ofrecer cuotas?', a: 'Sí. Con Mercado Pago tus clientes pagan en cuotas con tarjeta de crédito.' },
        { q: '¿El stock se actualiza solo?', a: 'Sí. Cada venta descuenta automáticamente. Sabés exactamente qué tenés disponible.' },
        { q: '¿Puedo hacer combos de regalo?', a: 'Sí. Creás packs de regalo combinando productos con un precio especial.' },
        { q: '¿Funciona para envío a domicilio?', a: 'Sí. El cliente pide online y coordinás envío o retiro en tu local.' },
      ],
      cta: { headline: 'Vendé juguetes', subtitle: 'las 24 horas del día.', description: 'Creá tu catálogo gratis, organizá por edad y categoría, y recibí pedidos sin parar.' },
    },

    libreria: {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Librería y Papelería — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para librerías y papelerías. Catálogo de útiles, libros y materiales con pedidos online. Empezá gratis.',
        keywords: ['vender librería online argentina', 'catálogo papelería online', 'tienda útiles escolares online', 'e-commerce librería', 'librería venta por internet'],
      },
      pill: '📚 Librería',
      heroTitle: 'Tu librería con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Vuelta a clases inmanejable', desc: 'Febrero es un caos. Colas, listas de útiles interminables, stock que se agota y padres desesperados.' },
        { title: 'Miles de productos sin catálogo', desc: 'Tenés 2000 artículos y el cliente pregunta si tenés tal lapicera o tal cuaderno. Buscás uno por uno.' },
        { title: 'Competencia con grandes cadenas', desc: 'Las grandes cadenas venden online con envío. Tu librería del barrio solo tiene mostrador.' },
      ],
      capabilities: [
        { icon: 'Search', title: 'Buscador de productos', desc: 'El cliente busca por nombre, marca o categoría y encuentra lo que necesita al instante.' },
        { icon: 'ShoppingBag', title: 'Listas de útiles', desc: 'Los padres arman la lista completa de útiles en el carrito y te mandan el pedido.' },
        { icon: 'Package', title: 'Stock de miles de items', desc: 'Cargá todos tus productos con stock. Cuando se agota, se marca automáticamente.' },
        { icon: 'Tag', title: 'Precios por mayor y menor', desc: 'Precios diferenciados para escuelas, empresas y público general.' },
        { icon: 'Globe', title: 'Presencia barrial online', desc: 'Tu link para que el barrio te encuentre y compre sin hacer cola.' },
        { icon: 'BarChart', title: 'Reportes de venta', desc: 'Productos más vendidos, categorías estrella y facturación semanal.' },
      ],
      subIndustries: ['Útiles escolares', 'Librería artística', 'Papelería comercial', 'Insumos de oficina', 'Libros y textos', 'Mochilas y cartucheras'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'La vuelta a clases fue otra cosa. Los padres armaron sus listas online y pasaron a retirar el pedido listo.', name: 'Graciela Ramos', role: 'Dueña', business: 'Librería Ramos', image: 'https://randomuser.me/api/portraits/women/109.jpg' },
        { quote: 'Cargué 1500 productos en una semana. Ahora los clientes buscan en el catálogo en vez de preguntarme uno por uno.', name: 'Daniel Flores', role: 'Gerente', business: 'Flores Papelería', image: 'https://randomuser.me/api/portraits/men/103.jpg' },
        { quote: 'Compito con las grandes cadenas porque ofrezco catálogo online y atención personalizada. Gano por servicio.', name: 'María Elena Soto', role: 'Fundadora', business: 'Soto Librería', image: 'https://randomuser.me/api/portraits/women/110.jpg' },
      ],
      faqs: [
        { q: '¿Puedo cargar miles de productos?', a: 'Sí. Sin límite de productos en los planes pagos. Cargá todo tu inventario.' },
        { q: '¿Funciona para listas de útiles escolares?', a: 'Sí. Los padres buscan cada artículo, lo agregan al carrito y arman la lista completa.' },
        { q: '¿Puedo tener precios por mayor?', a: 'Sí. Precios diferenciados para escuelas y empresas que compran en cantidad.' },
        { q: '¿Sirve para insumos de oficina?', a: 'Sí. Empresas buscan en tu catálogo y hacen pedidos regulares de insumos.' },
        { q: '¿El buscador encuentra por marca?', a: 'Sí. Buscá por nombre de producto, marca o categoría. Resultados instantáneos.' },
        { q: '¿Puedo preparar pedidos para retiro en local?', a: 'Sí. El cliente pide online y pasa a retirar. Sin colas, sin esperas.' },
      ],
      cta: { headline: 'Vendé útiles y libros', subtitle: 'sin hacer cola.', description: 'Creá tu catálogo gratis, cargá tus productos y que tus clientes compren online con retiro en local.' },
    },

    'indumentaria-deportiva': {
      accent: ACCENT, parentNicheUrl: PARENT_URL, parentNicheLabel: PARENT_LABEL,
      seo: {
        title: 'TurnoLink para Indumentaria Deportiva — Catálogo y Ventas Online',
        description: 'Plataforma de venta online para tiendas de ropa deportiva. Catálogo con talles, disciplinas y equipamiento. Empezá gratis.',
        keywords: ['vender ropa deportiva online argentina', 'catálogo indumentaria deportiva', 'tienda deportiva online', 'e-commerce deportes', 'vender zapatillas online'],
      },
      pill: '🏃 Indumentaria Deportiva',
      heroTitle: 'Tu tienda deportiva con',
      heroSubtitle: 'ventas las 24 horas.',
      painPoints: [
        { title: 'Talles y modelos por WhatsApp', desc: 'Cada cliente pregunta si queda tal talle del modelo X en color Y. Respondés uno por uno sin parar.' },
        { title: 'Temporadas y colecciones', desc: 'Llega la colección nueva y tenés que liquidar la anterior. Sin catálogo, todo es informal.' },
        { title: 'Clientes que no te encuentran', desc: 'Hay runners, crossfitters, futboleros buscando equipamiento y no te encuentran online.' },
      ],
      capabilities: [
        { icon: 'ShoppingBag', title: 'Catálogo por deporte', desc: 'Running, fútbol, fitness, tenis, natación. El cliente busca por su disciplina.' },
        { icon: 'Package', title: 'Stock por talle y color', desc: 'Talle S al XXL, cada color con su stock. El cliente ve qué queda antes de consultar.' },
        { icon: 'Tag', title: 'Liquidaciones fáciles', desc: 'Creá cupones de descuento para liquidar temporada anterior en días.' },
        { icon: 'Image', title: 'Fotos de producto', desc: 'Fotos con modelo, detalle de telas y tecnología. El deportista compra informado.' },
        { icon: 'CreditCard', title: 'Pagos en cuotas', desc: 'Zapatillas y equipamiento premium en cuotas con Mercado Pago.' },
        { icon: 'TrendingUp', title: 'Tendencias de venta', desc: 'Qué deporte vende más, qué talles se agotan primero, qué marcas son más buscadas.' },
      ],
      subIndustries: ['Running', 'Fútbol', 'Fitness y gym', 'Tenis y pádel', 'Natación', 'Outdoor y montaña'],
      pricing: SHARED_PRICING,
      testimonials: [
        { quote: 'Organicé el catálogo por deporte y las ventas se ordenaron solas. Los runners encuentran todo lo que necesitan juntos.', name: 'Esteban Romero', role: 'Dueño', business: 'Sport Zone ER', image: 'https://randomuser.me/api/portraits/men/104.jpg' },
        { quote: 'El stock por talle y color me ahorró horas de consultas. El cliente ve qué queda y decide solo.', name: 'Julieta Paredes', role: 'Gerente', business: 'Impulso Deportivo', image: 'https://randomuser.me/api/portraits/women/111.jpg' },
        { quote: 'Las liquidaciones de temporada las hago con cupones y se vende todo en una semana. Antes tardaba un mes.', name: 'Marcos Villanueva', role: 'Fundador', business: 'VN Sport', image: 'https://randomuser.me/api/portraits/men/105.jpg' },
      ],
      faqs: [
        { q: '¿Puedo organizar por disciplina deportiva?', a: 'Sí. Running, fútbol, fitness, tenis. El cliente busca por su deporte y encuentra todo junto.' },
        { q: '¿Funciona con talles y colores?', a: 'Sí. Cada producto con sus variantes de talle y color, cada una con stock independiente.' },
        { q: '¿Puedo hacer liquidaciones de temporada?', a: 'Sí. Cupones de descuento por categoría o producto con fecha de vencimiento.' },
        { q: '¿Los clientes pueden pagar en cuotas?', a: 'Sí. Con Mercado Pago tus clientes pagan en hasta 12 cuotas con tarjeta.' },
        { q: '¿Funciona para equipamiento además de ropa?', a: 'Sí. Cargá zapatillas, mochilas, accesorios, pelotas. Todo en el mismo catálogo.' },
        { q: '¿Puedo vender a clubes y equipos?', a: 'Sí. Compartís el catálogo con coordinadores de equipos para pedidos grupales.' },
      ],
      cta: { headline: 'Vendé deportes', subtitle: 'con catálogo profesional.', description: 'Creá tu catálogo gratis, organizá por deporte y talle, y empezá a vender online.' },
    },
  },
};

export default mercadoConfig;
